version: "2"
run:
  tests: false
  concurrency: 4
  go: '1.25.1'

# all available settings of specific linters
linters:
  enable:
    - bodyclose
    - containedctx
    - errname
    - gosec
    - unconvert
    - goconst
    - misspell
    - unparam
    - prealloc
    - copyloopvar
    - gochecknoinits
    - gocritic
    - dupl
    - gocyclo
    - lll
    - noctx
    - nolintlint
    - godot
    - whitespace
    - nlreturn
    - wsl
  settings:
    gosec:
      excludes:
        - G115
        - G602
    godot:
      exclude:
        - "^fixme:"
        - "^todo:"
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - printf
    gocyclo:
      min-complexity: 25
  #  maligned:
  #    # print struct with more effective memory layout or not, false by default
  #    suggest-new: true
    # misspell:
    #   locale: US
    # unparam:
    #   check-exported: true
    wsl:
      allow-assign-and-anything: true
    whitespace:
      multi-if: false
    gocritic:
      settings:
        hugeParam:
          sizeThreshold: 255
      enabled-checks:
        - sprintfQuotedString
        - badLock
        - badSorting
        - badSyncOnceFunc
        - boolExprSimplify
        - deferInLoop
        - rangeValCopy
        - unnamedResult
        - truncateCmp
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - preferDecodeRune
        - preferFprint
        - preferStringWriter
        - rangeExprCopy
        - ptrToRefParam
        - paramTypeCombine
        - nestingReduce
        - httpNoBody
        - evalOrder
        - sliceClear
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - scopelint
      - path: model/.*\.go
        linters:
          - lll
      - path: entity/.*\.go
        linters:
          - lll
    paths:
      - "mocks\\.go$"
      - assets
      - build
      - test

formatters:
  settings:
    gofumpt:
      extra-rules: true
    golines:
      shorten-comments: true

issues:
  fix: true
