// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/directory/v1/service.proto

package directoryv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DirectoryUser is the complete evaluation-relevant organization fact for one
// User. manager_user_id is absent when the User has no direct manager.
type DirectoryUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PositionId    uint64                 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	ManagerUserId *uint64                `protobuf:"varint,3,opt,name=manager_user_id,json=managerUserId,proto3,oneof" json:"manager_user_id,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryUser) Reset() {
	*x = DirectoryUser{}
	mi := &file_api_directory_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryUser) ProtoMessage() {}

func (x *DirectoryUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryUser.ProtoReflect.Descriptor instead.
func (*DirectoryUser) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *DirectoryUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DirectoryUser) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *DirectoryUser) GetManagerUserId() uint64 {
	if x != nil && x.ManagerUserId != nil {
		return *x.ManagerUserId
	}
	return 0
}

func (x *DirectoryUser) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetRosterSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRosterSnapshotRequest) Reset() {
	*x = GetRosterSnapshotRequest{}
	mi := &file_api_directory_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRosterSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRosterSnapshotRequest) ProtoMessage() {}

func (x *GetRosterSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRosterSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetRosterSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{1}
}

type GetRosterSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=snapshot_at,json=snapshotAt,proto3" json:"snapshot_at,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Users         []*DirectoryUser       `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRosterSnapshotResponse) Reset() {
	*x = GetRosterSnapshotResponse{}
	mi := &file_api_directory_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRosterSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRosterSnapshotResponse) ProtoMessage() {}

func (x *GetRosterSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRosterSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetRosterSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRosterSnapshotResponse) GetSnapshotAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotAt
	}
	return nil
}

func (x *GetRosterSnapshotResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetRosterSnapshotResponse) GetUsers() []*DirectoryUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_directory_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *DirectoryUser         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_directory_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *DirectoryUser {
	if x != nil {
		return x.User
	}
	return nil
}

type ListDirectReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerUserId uint64                 `protobuf:"varint,1,opt,name=manager_user_id,json=managerUserId,proto3" json:"manager_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectReportsRequest) Reset() {
	*x = ListDirectReportsRequest{}
	mi := &file_api_directory_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectReportsRequest) ProtoMessage() {}

func (x *ListDirectReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectReportsRequest.ProtoReflect.Descriptor instead.
func (*ListDirectReportsRequest) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListDirectReportsRequest) GetManagerUserId() uint64 {
	if x != nil {
		return x.ManagerUserId
	}
	return 0
}

type ListDirectReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=snapshot_at,json=snapshotAt,proto3" json:"snapshot_at,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UserIds       []uint64               `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectReportsResponse) Reset() {
	*x = ListDirectReportsResponse{}
	mi := &file_api_directory_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectReportsResponse) ProtoMessage() {}

func (x *ListDirectReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectReportsResponse.ProtoReflect.Descriptor instead.
func (*ListDirectReportsResponse) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirectReportsResponse) GetSnapshotAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotAt
	}
	return nil
}

func (x *ListDirectReportsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListDirectReportsResponse) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// DirectoryPosition is the minimal position catalog fact. It carries no user
// profiles, staff assignments or display names.
type DirectoryPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryPosition) Reset() {
	*x = DirectoryPosition{}
	mi := &file_api_directory_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryPosition) ProtoMessage() {}

func (x *DirectoryPosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryPosition.ProtoReflect.Descriptor instead.
func (*DirectoryPosition) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *DirectoryPosition) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    uint64                 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_api_directory_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetPositionRequest) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

type GetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *DirectoryPosition     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionResponse) Reset() {
	*x = GetPositionResponse{}
	mi := &file_api_directory_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResponse) ProtoMessage() {}

func (x *GetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_directory_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResponse.ProtoReflect.Descriptor instead.
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return file_api_directory_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetPositionResponse) GetPosition() *DirectoryPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_api_directory_v1_service_proto protoreflect.FileDescriptor

const file_api_directory_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/directory/v1/service.proto\x12\fdirectory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xbd\x01\n" +
	"\rDirectoryUser\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\x12(\n" +
	"\vposition_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\n" +
	"positionId\x124\n" +
	"\x0fmanager_user_id\x18\x03 \x01(\x04B\a\xfaB\x042\x02 \x00H\x00R\rmanagerUserId\x88\x01\x01\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06activeB\x12\n" +
	"\x10_manager_user_id\"\x1a\n" +
	"\x18GetRosterSnapshotRequest\"\xd1\x01\n" +
	"\x19GetRosterSnapshotResponse\x12E\n" +
	"\vsnapshot_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\n" +
	"snapshotAt\x12/\n" +
	"\aversion\x18\x02 \x01(\tB\x15\xfaB\x12r\x102\x0e^[0-9a-f]{64}$R\aversion\x12<\n" +
	"\x05users\x18\x03 \x03(\v2\x1b.directory.v1.DirectoryUserB\t\xfaB\x06\x92\x01\x03\x10\x88'R\x05users\"2\n" +
	"\x0eGetUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\"L\n" +
	"\x0fGetUserResponse\x129\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.directory.v1.DirectoryUserB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04user\"K\n" +
	"\x18ListDirectReportsRequest\x12/\n" +
	"\x0fmanager_user_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\rmanagerUserId\"\xc1\x01\n" +
	"\x19ListDirectReportsResponse\x12E\n" +
	"\vsnapshot_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\n" +
	"snapshotAt\x12/\n" +
	"\aversion\x18\x02 \x01(\tB\x15\xfaB\x12r\x102\x0e^[0-9a-f]{64}$R\aversion\x12,\n" +
	"\buser_ids\x18\x03 \x03(\x04B\x11\xfaB\x0e\x92\x01\v\x10\x88'\x18\x01\"\x042\x02 \x00R\auserIds\",\n" +
	"\x11DirectoryPosition\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x02id\">\n" +
	"\x12GetPositionRequest\x12(\n" +
	"\vposition_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\n" +
	"positionId\"\\\n" +
	"\x13GetPositionResponse\x12E\n" +
	"\bposition\x18\x01 \x01(\v2\x1f.directory.v1.DirectoryPositionB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bposition2\xfa\x02\n" +
	"\x10DirectoryService\x12d\n" +
	"\x11GetRosterSnapshot\x12&.directory.v1.GetRosterSnapshotRequest\x1a'.directory.v1.GetRosterSnapshotResponse\x12F\n" +
	"\aGetUser\x12\x1c.directory.v1.GetUserRequest\x1a\x1d.directory.v1.GetUserResponse\x12d\n" +
	"\x11ListDirectReports\x12&.directory.v1.ListDirectReportsRequest\x1a'.directory.v1.ListDirectReportsResponse\x12R\n" +
	"\vGetPosition\x12 .directory.v1.GetPositionRequest\x1a!.directory.v1.GetPositionResponseBAZ?github.com/SOTBI-LLC/sotbi.lib/pkg/api/directory/v1;directoryv1b\x06proto3"

var (
	file_api_directory_v1_service_proto_rawDescOnce sync.Once
	file_api_directory_v1_service_proto_rawDescData []byte
)

func file_api_directory_v1_service_proto_rawDescGZIP() []byte {
	file_api_directory_v1_service_proto_rawDescOnce.Do(func() {
		file_api_directory_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_directory_v1_service_proto_rawDesc), len(file_api_directory_v1_service_proto_rawDesc)))
	})
	return file_api_directory_v1_service_proto_rawDescData
}

var file_api_directory_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_directory_v1_service_proto_goTypes = []any{
	(*DirectoryUser)(nil),             // 0: directory.v1.DirectoryUser
	(*GetRosterSnapshotRequest)(nil),  // 1: directory.v1.GetRosterSnapshotRequest
	(*GetRosterSnapshotResponse)(nil), // 2: directory.v1.GetRosterSnapshotResponse
	(*GetUserRequest)(nil),            // 3: directory.v1.GetUserRequest
	(*GetUserResponse)(nil),           // 4: directory.v1.GetUserResponse
	(*ListDirectReportsRequest)(nil),  // 5: directory.v1.ListDirectReportsRequest
	(*ListDirectReportsResponse)(nil), // 6: directory.v1.ListDirectReportsResponse
	(*DirectoryPosition)(nil),         // 7: directory.v1.DirectoryPosition
	(*GetPositionRequest)(nil),        // 8: directory.v1.GetPositionRequest
	(*GetPositionResponse)(nil),       // 9: directory.v1.GetPositionResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_api_directory_v1_service_proto_depIdxs = []int32{
	10, // 0: directory.v1.GetRosterSnapshotResponse.snapshot_at:type_name -> google.protobuf.Timestamp
	0,  // 1: directory.v1.GetRosterSnapshotResponse.users:type_name -> directory.v1.DirectoryUser
	0,  // 2: directory.v1.GetUserResponse.user:type_name -> directory.v1.DirectoryUser
	10, // 3: directory.v1.ListDirectReportsResponse.snapshot_at:type_name -> google.protobuf.Timestamp
	7,  // 4: directory.v1.GetPositionResponse.position:type_name -> directory.v1.DirectoryPosition
	1,  // 5: directory.v1.DirectoryService.GetRosterSnapshot:input_type -> directory.v1.GetRosterSnapshotRequest
	3,  // 6: directory.v1.DirectoryService.GetUser:input_type -> directory.v1.GetUserRequest
	5,  // 7: directory.v1.DirectoryService.ListDirectReports:input_type -> directory.v1.ListDirectReportsRequest
	8,  // 8: directory.v1.DirectoryService.GetPosition:input_type -> directory.v1.GetPositionRequest
	2,  // 9: directory.v1.DirectoryService.GetRosterSnapshot:output_type -> directory.v1.GetRosterSnapshotResponse
	4,  // 10: directory.v1.DirectoryService.GetUser:output_type -> directory.v1.GetUserResponse
	6,  // 11: directory.v1.DirectoryService.ListDirectReports:output_type -> directory.v1.ListDirectReportsResponse
	9,  // 12: directory.v1.DirectoryService.GetPosition:output_type -> directory.v1.GetPositionResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_directory_v1_service_proto_init() }
func file_api_directory_v1_service_proto_init() {
	if File_api_directory_v1_service_proto != nil {
		return
	}
	file_api_directory_v1_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_directory_v1_service_proto_rawDesc), len(file_api_directory_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_directory_v1_service_proto_goTypes,
		DependencyIndexes: file_api_directory_v1_service_proto_depIdxs,
		MessageInfos:      file_api_directory_v1_service_proto_msgTypes,
	}.Build()
	File_api_directory_v1_service_proto = out.File
	file_api_directory_v1_service_proto_goTypes = nil
	file_api_directory_v1_service_proto_depIdxs = nil
}
