// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: api/directory/v1/service.proto

package directoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DirectoryService_GetRosterSnapshot_FullMethodName = "/directory.v1.DirectoryService/GetRosterSnapshot"
	DirectoryService_GetUser_FullMethodName           = "/directory.v1.DirectoryService/GetUser"
	DirectoryService_ListDirectReports_FullMethodName = "/directory.v1.DirectoryService/ListDirectReports"
)

// DirectoryServiceClient is the client API for DirectoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DirectoryService provides one bounded, current, read-only organization view.
//
// Errors use standard gRPC status codes with google.rpc.ErrorInfo reasons:
// USER_NOT_FOUND, DIRECTORY_DATA_INCONSISTENT, ROSTER_LIMIT_EXCEEDED,
// DIRECT_REPORT_LIMIT_EXCEEDED, RATE_LIMITED, and AUTH_ROLE_MISSING. Only
// temporary RATE_LIMITED responses include google.rpc.RetryInfo.
type DirectoryServiceClient interface {
	GetRosterSnapshot(ctx context.Context, in *GetRosterSnapshotRequest, opts ...grpc.CallOption) (*GetRosterSnapshotResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListDirectReports(ctx context.Context, in *ListDirectReportsRequest, opts ...grpc.CallOption) (*ListDirectReportsResponse, error)
}

type directoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectoryServiceClient(cc grpc.ClientConnInterface) DirectoryServiceClient {
	return &directoryServiceClient{cc}
}

func (c *directoryServiceClient) GetRosterSnapshot(ctx context.Context, in *GetRosterSnapshotRequest, opts ...grpc.CallOption) (*GetRosterSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRosterSnapshotResponse)
	err := c.cc.Invoke(ctx, DirectoryService_GetRosterSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, DirectoryService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryServiceClient) ListDirectReports(ctx context.Context, in *ListDirectReportsRequest, opts ...grpc.CallOption) (*ListDirectReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectReportsResponse)
	err := c.cc.Invoke(ctx, DirectoryService_ListDirectReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryServiceServer is the server API for DirectoryService service.
// All implementations must embed UnimplementedDirectoryServiceServer
// for forward compatibility.
//
// DirectoryService provides one bounded, current, read-only organization view.
//
// Errors use standard gRPC status codes with google.rpc.ErrorInfo reasons:
// USER_NOT_FOUND, DIRECTORY_DATA_INCONSISTENT, ROSTER_LIMIT_EXCEEDED,
// DIRECT_REPORT_LIMIT_EXCEEDED, RATE_LIMITED, and AUTH_ROLE_MISSING. Only
// temporary RATE_LIMITED responses include google.rpc.RetryInfo.
type DirectoryServiceServer interface {
	GetRosterSnapshot(context.Context, *GetRosterSnapshotRequest) (*GetRosterSnapshotResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ListDirectReports(context.Context, *ListDirectReportsRequest) (*ListDirectReportsResponse, error)
	mustEmbedUnimplementedDirectoryServiceServer()
}

// UnimplementedDirectoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectoryServiceServer struct{}

func (UnimplementedDirectoryServiceServer) GetRosterSnapshot(context.Context, *GetRosterSnapshotRequest) (*GetRosterSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRosterSnapshot not implemented")
}
func (UnimplementedDirectoryServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedDirectoryServiceServer) ListDirectReports(context.Context, *ListDirectReportsRequest) (*ListDirectReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectReports not implemented")
}
func (UnimplementedDirectoryServiceServer) mustEmbedUnimplementedDirectoryServiceServer() {}
func (UnimplementedDirectoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDirectoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectoryServiceServer will
// result in compilation errors.
type UnsafeDirectoryServiceServer interface {
	mustEmbedUnimplementedDirectoryServiceServer()
}

func RegisterDirectoryServiceServer(s grpc.ServiceRegistrar, srv DirectoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDirectoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirectoryService_ServiceDesc, srv)
}

func _DirectoryService_GetRosterSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRosterSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).GetRosterSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_GetRosterSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).GetRosterSnapshot(ctx, req.(*GetRosterSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryService_ListDirectReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).ListDirectReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_ListDirectReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).ListDirectReports(ctx, req.(*ListDirectReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DirectoryService_ServiceDesc is the grpc.ServiceDesc for DirectoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "directory.v1.DirectoryService",
	HandlerType: (*DirectoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRosterSnapshot",
			Handler:    _DirectoryService_GetRosterSnapshot_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _DirectoryService_GetUser_Handler,
		},
		{
			MethodName: "ListDirectReports",
			Handler:    _DirectoryService_ListDirectReports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/directory/v1/service.proto",
}
