// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/directory/v1/service.proto

package directoryv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DirectoryUser with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DirectoryUser) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DirectoryUser with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DirectoryUserMultiError, or
// nil if none found.
func (m *DirectoryUser) ValidateAll() error {
	return m.validate(true)
}

func (m *DirectoryUser) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := DirectoryUserValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPositionId() <= 0 {
		err := DirectoryUserValidationError{
			field:  "PositionId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Active

	if m.ManagerUserId != nil {

		if m.GetManagerUserId() <= 0 {
			err := DirectoryUserValidationError{
				field:  "ManagerUserId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return DirectoryUserMultiError(errors)
	}

	return nil
}

// DirectoryUserMultiError is an error wrapping multiple validation errors
// returned by DirectoryUser.ValidateAll() if the designated constraints
// aren't met.
type DirectoryUserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DirectoryUserMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DirectoryUserMultiError) AllErrors() []error { return m }

// DirectoryUserValidationError is the validation error returned by
// DirectoryUser.Validate if the designated constraints aren't met.
type DirectoryUserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DirectoryUserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DirectoryUserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DirectoryUserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DirectoryUserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DirectoryUserValidationError) ErrorName() string { return "DirectoryUserValidationError" }

// Error satisfies the builtin error interface
func (e DirectoryUserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDirectoryUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DirectoryUserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DirectoryUserValidationError{}

// Validate checks the field values on GetRosterSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRosterSnapshotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRosterSnapshotRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRosterSnapshotRequestMultiError, or nil if none found.
func (m *GetRosterSnapshotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRosterSnapshotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetRosterSnapshotRequestMultiError(errors)
	}

	return nil
}

// GetRosterSnapshotRequestMultiError is an error wrapping multiple validation
// errors returned by GetRosterSnapshotRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRosterSnapshotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRosterSnapshotRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRosterSnapshotRequestMultiError) AllErrors() []error { return m }

// GetRosterSnapshotRequestValidationError is the validation error returned by
// GetRosterSnapshotRequest.Validate if the designated constraints aren't met.
type GetRosterSnapshotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRosterSnapshotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRosterSnapshotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRosterSnapshotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRosterSnapshotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRosterSnapshotRequestValidationError) ErrorName() string {
	return "GetRosterSnapshotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRosterSnapshotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRosterSnapshotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRosterSnapshotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRosterSnapshotRequestValidationError{}

// Validate checks the field values on GetRosterSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRosterSnapshotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRosterSnapshotResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRosterSnapshotResponseMultiError, or nil if none found.
func (m *GetRosterSnapshotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRosterSnapshotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSnapshotAt() == nil {
		err := GetRosterSnapshotResponseValidationError{
			field:  "SnapshotAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_GetRosterSnapshotResponse_Version_Pattern.MatchString(m.GetVersion()) {
		err := GetRosterSnapshotResponseValidationError{
			field:  "Version",
			reason: "value does not match regex pattern \"^[0-9a-f]{64}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetUsers()) > 5000 {
		err := GetRosterSnapshotResponseValidationError{
			field:  "Users",
			reason: "value must contain no more than 5000 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetUsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetRosterSnapshotResponseValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetRosterSnapshotResponseValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetRosterSnapshotResponseValidationError{
					field:  fmt.Sprintf("Users[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetRosterSnapshotResponseMultiError(errors)
	}

	return nil
}

// GetRosterSnapshotResponseMultiError is an error wrapping multiple validation
// errors returned by GetRosterSnapshotResponse.ValidateAll() if the
// designated constraints aren't met.
type GetRosterSnapshotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRosterSnapshotResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRosterSnapshotResponseMultiError) AllErrors() []error { return m }

// GetRosterSnapshotResponseValidationError is the validation error returned by
// GetRosterSnapshotResponse.Validate if the designated constraints aren't met.
type GetRosterSnapshotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRosterSnapshotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRosterSnapshotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRosterSnapshotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRosterSnapshotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRosterSnapshotResponseValidationError) ErrorName() string {
	return "GetRosterSnapshotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRosterSnapshotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRosterSnapshotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRosterSnapshotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRosterSnapshotResponseValidationError{}

var _GetRosterSnapshotResponse_Version_Pattern = regexp.MustCompile("^[0-9a-f]{64}$")

// Validate checks the field values on GetUserRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetUserRequestMultiError,
// or nil if none found.
func (m *GetUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := GetUserRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserRequestMultiError(errors)
	}

	return nil
}

// GetUserRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserRequestMultiError) AllErrors() []error { return m }

// GetUserRequestValidationError is the validation error returned by
// GetUserRequest.Validate if the designated constraints aren't met.
type GetUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserRequestValidationError) ErrorName() string { return "GetUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserRequestValidationError{}

// Validate checks the field values on GetUserResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserResponseMultiError, or nil if none found.
func (m *GetUserResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUser() == nil {
		err := GetUserResponseValidationError{
			field:  "User",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserResponseMultiError(errors)
	}

	return nil
}

// GetUserResponseMultiError is an error wrapping multiple validation errors
// returned by GetUserResponse.ValidateAll() if the designated constraints
// aren't met.
type GetUserResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserResponseMultiError) AllErrors() []error { return m }

// GetUserResponseValidationError is the validation error returned by
// GetUserResponse.Validate if the designated constraints aren't met.
type GetUserResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserResponseValidationError) ErrorName() string { return "GetUserResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetUserResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserResponseValidationError{}

// Validate checks the field values on ListDirectReportsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDirectReportsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDirectReportsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDirectReportsRequestMultiError, or nil if none found.
func (m *ListDirectReportsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDirectReportsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetManagerUserId() <= 0 {
		err := ListDirectReportsRequestValidationError{
			field:  "ManagerUserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListDirectReportsRequestMultiError(errors)
	}

	return nil
}

// ListDirectReportsRequestMultiError is an error wrapping multiple validation
// errors returned by ListDirectReportsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListDirectReportsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDirectReportsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDirectReportsRequestMultiError) AllErrors() []error { return m }

// ListDirectReportsRequestValidationError is the validation error returned by
// ListDirectReportsRequest.Validate if the designated constraints aren't met.
type ListDirectReportsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDirectReportsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDirectReportsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDirectReportsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDirectReportsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDirectReportsRequestValidationError) ErrorName() string {
	return "ListDirectReportsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListDirectReportsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDirectReportsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDirectReportsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDirectReportsRequestValidationError{}

// Validate checks the field values on ListDirectReportsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDirectReportsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDirectReportsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDirectReportsResponseMultiError, or nil if none found.
func (m *ListDirectReportsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDirectReportsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSnapshotAt() == nil {
		err := ListDirectReportsResponseValidationError{
			field:  "SnapshotAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_ListDirectReportsResponse_Version_Pattern.MatchString(m.GetVersion()) {
		err := ListDirectReportsResponseValidationError{
			field:  "Version",
			reason: "value does not match regex pattern \"^[0-9a-f]{64}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetUserIds()) > 5000 {
		err := ListDirectReportsResponseValidationError{
			field:  "UserIds",
			reason: "value must contain no more than 5000 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	_ListDirectReportsResponse_UserIds_Unique := make(map[uint64]struct{}, len(m.GetUserIds()))

	for idx, item := range m.GetUserIds() {
		_, _ = idx, item

		if _, exists := _ListDirectReportsResponse_UserIds_Unique[item]; exists {
			err := ListDirectReportsResponseValidationError{
				field:  fmt.Sprintf("UserIds[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_ListDirectReportsResponse_UserIds_Unique[item] = struct{}{}
		}

		if item <= 0 {
			err := ListDirectReportsResponseValidationError{
				field:  fmt.Sprintf("UserIds[%v]", idx),
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ListDirectReportsResponseMultiError(errors)
	}

	return nil
}

// ListDirectReportsResponseMultiError is an error wrapping multiple validation
// errors returned by ListDirectReportsResponse.ValidateAll() if the
// designated constraints aren't met.
type ListDirectReportsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDirectReportsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDirectReportsResponseMultiError) AllErrors() []error { return m }

// ListDirectReportsResponseValidationError is the validation error returned by
// ListDirectReportsResponse.Validate if the designated constraints aren't met.
type ListDirectReportsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDirectReportsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDirectReportsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDirectReportsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDirectReportsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDirectReportsResponseValidationError) ErrorName() string {
	return "ListDirectReportsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListDirectReportsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDirectReportsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDirectReportsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDirectReportsResponseValidationError{}

var _ListDirectReportsResponse_Version_Pattern = regexp.MustCompile("^[0-9a-f]{64}$")
