// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: motivation/service.proto

package motivation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Motivation_ListBaseCriteria_FullMethodName          = "/motivation.Motivation/ListBaseCriteria"
	Motivation_CreateBaseCriteria_FullMethodName        = "/motivation.Motivation/CreateBaseCriteria"
	Motivation_UpdateBaseCriteria_FullMethodName        = "/motivation.Motivation/UpdateBaseCriteria"
	Motivation_ListPerformancePeriods_FullMethodName    = "/motivation.Motivation/ListPerformancePeriods"
	Motivation_UpsertPerformancePeriod_FullMethodName   = "/motivation.Motivation/UpsertPerformancePeriod"
	Motivation_ListPerformanceCriteria_FullMethodName   = "/motivation.Motivation/ListPerformanceCriteria"
	Motivation_CreatePerformanceCriteria_FullMethodName = "/motivation.Motivation/CreatePerformanceCriteria"
	Motivation_UpdatePerformanceCriteria_FullMethodName = "/motivation.Motivation/UpdatePerformanceCriteria"
	Motivation_UpsertUserPerformance_FullMethodName     = "/motivation.Motivation/UpsertUserPerformance"
	Motivation_ListUserPerformance_FullMethodName       = "/motivation.Motivation/ListUserPerformance"
	Motivation_CalculateUserPercentage_FullMethodName   = "/motivation.Motivation/CalculateUserPercentage"
)

// MotivationClient is the client API for Motivation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MotivationClient interface {
	ListBaseCriteria(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BaseCriteriaList, error)
	CreateBaseCriteria(ctx context.Context, in *CreateBaseCriteriaRequest, opts ...grpc.CallOption) (*BaseCriteria, error)
	UpdateBaseCriteria(ctx context.Context, in *UpdateBaseCriteriaRequest, opts ...grpc.CallOption) (*BaseCriteria, error)
	ListPerformancePeriods(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PerformancePeriodsList, error)
	UpsertPerformancePeriod(ctx context.Context, in *UpsertPerformancePeriodRequest, opts ...grpc.CallOption) (*PerformancePeriod, error)
	ListPerformanceCriteria(ctx context.Context, in *ListPerformanceCriteriaRequest, opts ...grpc.CallOption) (*PerformanceCriteriaList, error)
	CreatePerformanceCriteria(ctx context.Context, in *CreatePerformanceCriteriaRequest, opts ...grpc.CallOption) (*PerformanceCriteria, error)
	UpdatePerformanceCriteria(ctx context.Context, in *UpdatePerformanceCriteriaRequest, opts ...grpc.CallOption) (*PerformanceCriteria, error)
	UpsertUserPerformance(ctx context.Context, in *UpsertUserPerformanceRequest, opts ...grpc.CallOption) (*UserPerformance, error)
	ListUserPerformance(ctx context.Context, in *ListUserPerformanceRequest, opts ...grpc.CallOption) (*UserPerformanceList, error)
	CalculateUserPercentage(ctx context.Context, in *CalculateUserPercentageRequest, opts ...grpc.CallOption) (*UserPercentage, error)
}

type motivationClient struct {
	cc grpc.ClientConnInterface
}

func NewMotivationClient(cc grpc.ClientConnInterface) MotivationClient {
	return &motivationClient{cc}
}

func (c *motivationClient) ListBaseCriteria(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BaseCriteriaList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCriteriaList)
	err := c.cc.Invoke(ctx, Motivation_ListBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) CreateBaseCriteria(ctx context.Context, in *CreateBaseCriteriaRequest, opts ...grpc.CallOption) (*BaseCriteria, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCriteria)
	err := c.cc.Invoke(ctx, Motivation_CreateBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) UpdateBaseCriteria(ctx context.Context, in *UpdateBaseCriteriaRequest, opts ...grpc.CallOption) (*BaseCriteria, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseCriteria)
	err := c.cc.Invoke(ctx, Motivation_UpdateBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) ListPerformancePeriods(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PerformancePeriodsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformancePeriodsList)
	err := c.cc.Invoke(ctx, Motivation_ListPerformancePeriods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) UpsertPerformancePeriod(ctx context.Context, in *UpsertPerformancePeriodRequest, opts ...grpc.CallOption) (*PerformancePeriod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformancePeriod)
	err := c.cc.Invoke(ctx, Motivation_UpsertPerformancePeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) ListPerformanceCriteria(ctx context.Context, in *ListPerformanceCriteriaRequest, opts ...grpc.CallOption) (*PerformanceCriteriaList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceCriteriaList)
	err := c.cc.Invoke(ctx, Motivation_ListPerformanceCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) CreatePerformanceCriteria(ctx context.Context, in *CreatePerformanceCriteriaRequest, opts ...grpc.CallOption) (*PerformanceCriteria, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceCriteria)
	err := c.cc.Invoke(ctx, Motivation_CreatePerformanceCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) UpdatePerformanceCriteria(ctx context.Context, in *UpdatePerformanceCriteriaRequest, opts ...grpc.CallOption) (*PerformanceCriteria, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceCriteria)
	err := c.cc.Invoke(ctx, Motivation_UpdatePerformanceCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) UpsertUserPerformance(ctx context.Context, in *UpsertUserPerformanceRequest, opts ...grpc.CallOption) (*UserPerformance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPerformance)
	err := c.cc.Invoke(ctx, Motivation_UpsertUserPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) ListUserPerformance(ctx context.Context, in *ListUserPerformanceRequest, opts ...grpc.CallOption) (*UserPerformanceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPerformanceList)
	err := c.cc.Invoke(ctx, Motivation_ListUserPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *motivationClient) CalculateUserPercentage(ctx context.Context, in *CalculateUserPercentageRequest, opts ...grpc.CallOption) (*UserPercentage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPercentage)
	err := c.cc.Invoke(ctx, Motivation_CalculateUserPercentage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MotivationServer is the server API for Motivation service.
// All implementations must embed UnimplementedMotivationServer
// for forward compatibility.
type MotivationServer interface {
	ListBaseCriteria(context.Context, *emptypb.Empty) (*BaseCriteriaList, error)
	CreateBaseCriteria(context.Context, *CreateBaseCriteriaRequest) (*BaseCriteria, error)
	UpdateBaseCriteria(context.Context, *UpdateBaseCriteriaRequest) (*BaseCriteria, error)
	ListPerformancePeriods(context.Context, *emptypb.Empty) (*PerformancePeriodsList, error)
	UpsertPerformancePeriod(context.Context, *UpsertPerformancePeriodRequest) (*PerformancePeriod, error)
	ListPerformanceCriteria(context.Context, *ListPerformanceCriteriaRequest) (*PerformanceCriteriaList, error)
	CreatePerformanceCriteria(context.Context, *CreatePerformanceCriteriaRequest) (*PerformanceCriteria, error)
	UpdatePerformanceCriteria(context.Context, *UpdatePerformanceCriteriaRequest) (*PerformanceCriteria, error)
	UpsertUserPerformance(context.Context, *UpsertUserPerformanceRequest) (*UserPerformance, error)
	ListUserPerformance(context.Context, *ListUserPerformanceRequest) (*UserPerformanceList, error)
	CalculateUserPercentage(context.Context, *CalculateUserPercentageRequest) (*UserPercentage, error)
	mustEmbedUnimplementedMotivationServer()
}

// UnimplementedMotivationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMotivationServer struct{}

func (UnimplementedMotivationServer) ListBaseCriteria(context.Context, *emptypb.Empty) (*BaseCriteriaList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBaseCriteria not implemented")
}
func (UnimplementedMotivationServer) CreateBaseCriteria(context.Context, *CreateBaseCriteriaRequest) (*BaseCriteria, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBaseCriteria not implemented")
}
func (UnimplementedMotivationServer) UpdateBaseCriteria(context.Context, *UpdateBaseCriteriaRequest) (*BaseCriteria, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBaseCriteria not implemented")
}
func (UnimplementedMotivationServer) ListPerformancePeriods(context.Context, *emptypb.Empty) (*PerformancePeriodsList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPerformancePeriods not implemented")
}
func (UnimplementedMotivationServer) UpsertPerformancePeriod(context.Context, *UpsertPerformancePeriodRequest) (*PerformancePeriod, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPerformancePeriod not implemented")
}
func (UnimplementedMotivationServer) ListPerformanceCriteria(context.Context, *ListPerformanceCriteriaRequest) (*PerformanceCriteriaList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPerformanceCriteria not implemented")
}
func (UnimplementedMotivationServer) CreatePerformanceCriteria(context.Context, *CreatePerformanceCriteriaRequest) (*PerformanceCriteria, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePerformanceCriteria not implemented")
}
func (UnimplementedMotivationServer) UpdatePerformanceCriteria(context.Context, *UpdatePerformanceCriteriaRequest) (*PerformanceCriteria, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePerformanceCriteria not implemented")
}
func (UnimplementedMotivationServer) UpsertUserPerformance(context.Context, *UpsertUserPerformanceRequest) (*UserPerformance, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertUserPerformance not implemented")
}
func (UnimplementedMotivationServer) ListUserPerformance(context.Context, *ListUserPerformanceRequest) (*UserPerformanceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserPerformance not implemented")
}
func (UnimplementedMotivationServer) CalculateUserPercentage(context.Context, *CalculateUserPercentageRequest) (*UserPercentage, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateUserPercentage not implemented")
}
func (UnimplementedMotivationServer) mustEmbedUnimplementedMotivationServer() {}
func (UnimplementedMotivationServer) testEmbeddedByValue()                    {}

// UnsafeMotivationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MotivationServer will
// result in compilation errors.
type UnsafeMotivationServer interface {
	mustEmbedUnimplementedMotivationServer()
}

func RegisterMotivationServer(s grpc.ServiceRegistrar, srv MotivationServer) {
	// If the following call panics, it indicates UnimplementedMotivationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Motivation_ServiceDesc, srv)
}

func _Motivation_ListBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).ListBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_ListBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).ListBaseCriteria(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_CreateBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBaseCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).CreateBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_CreateBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).CreateBaseCriteria(ctx, req.(*CreateBaseCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_UpdateBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBaseCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).UpdateBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_UpdateBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).UpdateBaseCriteria(ctx, req.(*UpdateBaseCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_ListPerformancePeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).ListPerformancePeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_ListPerformancePeriods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).ListPerformancePeriods(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_UpsertPerformancePeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPerformancePeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).UpsertPerformancePeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_UpsertPerformancePeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).UpsertPerformancePeriod(ctx, req.(*UpsertPerformancePeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_ListPerformanceCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPerformanceCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).ListPerformanceCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_ListPerformanceCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).ListPerformanceCriteria(ctx, req.(*ListPerformanceCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_CreatePerformanceCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePerformanceCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).CreatePerformanceCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_CreatePerformanceCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).CreatePerformanceCriteria(ctx, req.(*CreatePerformanceCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_UpdatePerformanceCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePerformanceCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).UpdatePerformanceCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_UpdatePerformanceCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).UpdatePerformanceCriteria(ctx, req.(*UpdatePerformanceCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_UpsertUserPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUserPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).UpsertUserPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_UpsertUserPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).UpsertUserPerformance(ctx, req.(*UpsertUserPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_ListUserPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).ListUserPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_ListUserPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).ListUserPerformance(ctx, req.(*ListUserPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Motivation_CalculateUserPercentage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateUserPercentageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotivationServer).CalculateUserPercentage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Motivation_CalculateUserPercentage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotivationServer).CalculateUserPercentage(ctx, req.(*CalculateUserPercentageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Motivation_ServiceDesc is the grpc.ServiceDesc for Motivation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Motivation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "motivation.Motivation",
	HandlerType: (*MotivationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBaseCriteria",
			Handler:    _Motivation_ListBaseCriteria_Handler,
		},
		{
			MethodName: "CreateBaseCriteria",
			Handler:    _Motivation_CreateBaseCriteria_Handler,
		},
		{
			MethodName: "UpdateBaseCriteria",
			Handler:    _Motivation_UpdateBaseCriteria_Handler,
		},
		{
			MethodName: "ListPerformancePeriods",
			Handler:    _Motivation_ListPerformancePeriods_Handler,
		},
		{
			MethodName: "UpsertPerformancePeriod",
			Handler:    _Motivation_UpsertPerformancePeriod_Handler,
		},
		{
			MethodName: "ListPerformanceCriteria",
			Handler:    _Motivation_ListPerformanceCriteria_Handler,
		},
		{
			MethodName: "CreatePerformanceCriteria",
			Handler:    _Motivation_CreatePerformanceCriteria_Handler,
		},
		{
			MethodName: "UpdatePerformanceCriteria",
			Handler:    _Motivation_UpdatePerformanceCriteria_Handler,
		},
		{
			MethodName: "UpsertUserPerformance",
			Handler:    _Motivation_UpsertUserPerformance_Handler,
		},
		{
			MethodName: "ListUserPerformance",
			Handler:    _Motivation_ListUserPerformance_Handler,
		},
		{
			MethodName: "CalculateUserPercentage",
			Handler:    _Motivation_CalculateUserPercentage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "motivation/service.proto",
}
