// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: motivation/service.proto

package motivation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseCriteria) Reset() {
	*x = BaseCriteria{}
	mi := &file_motivation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseCriteria) ProtoMessage() {}

func (x *BaseCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseCriteria.ProtoReflect.Descriptor instead.
func (*BaseCriteria) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{0}
}

func (x *BaseCriteria) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseCriteria) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseCriteria) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BaseCriteria) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *BaseCriteria) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *BaseCriteria) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *BaseCriteria) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

type BaseCriteriaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BaseCriteria        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseCriteriaList) Reset() {
	*x = BaseCriteriaList{}
	mi := &file_motivation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseCriteriaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseCriteriaList) ProtoMessage() {}

func (x *BaseCriteriaList) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseCriteriaList.ProtoReflect.Descriptor instead.
func (*BaseCriteriaList) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{1}
}

func (x *BaseCriteriaList) GetItems() []*BaseCriteria {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateBaseCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,3,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBaseCriteriaRequest) Reset() {
	*x = CreateBaseCriteriaRequest{}
	mi := &file_motivation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBaseCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseCriteriaRequest) ProtoMessage() {}

func (x *CreateBaseCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseCriteriaRequest.ProtoReflect.Descriptor instead.
func (*CreateBaseCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBaseCriteriaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBaseCriteriaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBaseCriteriaRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *CreateBaseCriteriaRequest) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *CreateBaseCriteriaRequest) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type UpdateBaseCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBaseCriteriaRequest) Reset() {
	*x = UpdateBaseCriteriaRequest{}
	mi := &file_motivation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBaseCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBaseCriteriaRequest) ProtoMessage() {}

func (x *UpdateBaseCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBaseCriteriaRequest.ProtoReflect.Descriptor instead.
func (*UpdateBaseCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBaseCriteriaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBaseCriteriaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBaseCriteriaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBaseCriteriaRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *UpdateBaseCriteriaRequest) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *UpdateBaseCriteriaRequest) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type PerformancePeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformancePeriod) Reset() {
	*x = PerformancePeriod{}
	mi := &file_motivation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformancePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformancePeriod) ProtoMessage() {}

func (x *PerformancePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformancePeriod.ProtoReflect.Descriptor instead.
func (*PerformancePeriod) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{4}
}

func (x *PerformancePeriod) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PerformancePeriod) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *PerformancePeriod) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *PerformancePeriod) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PerformancePeriod) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *PerformancePeriod) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *PerformancePeriod) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

type PerformancePeriodID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformancePeriodID) Reset() {
	*x = PerformancePeriodID{}
	mi := &file_motivation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformancePeriodID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformancePeriodID) ProtoMessage() {}

func (x *PerformancePeriodID) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformancePeriodID.ProtoReflect.Descriptor instead.
func (*PerformancePeriodID) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{5}
}

func (x *PerformancePeriodID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PerformancePeriodsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PerformancePeriod   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformancePeriodsList) Reset() {
	*x = PerformancePeriodsList{}
	mi := &file_motivation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformancePeriodsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformancePeriodsList) ProtoMessage() {}

func (x *PerformancePeriodsList) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformancePeriodsList.ProtoReflect.Descriptor instead.
func (*PerformancePeriodsList) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{6}
}

func (x *PerformancePeriodsList) GetItems() []*PerformancePeriod {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpsertPerformancePeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPerformancePeriodRequest) Reset() {
	*x = UpsertPerformancePeriodRequest{}
	mi := &file_motivation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPerformancePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPerformancePeriodRequest) ProtoMessage() {}

func (x *UpsertPerformancePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPerformancePeriodRequest.ProtoReflect.Descriptor instead.
func (*UpsertPerformancePeriodRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertPerformancePeriodRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpsertPerformancePeriodRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *UpsertPerformancePeriodRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpsertPerformancePeriodRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *UpsertPerformancePeriodRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

type PerformanceCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,8,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	IsAbsolute    bool                   `protobuf:"varint,9,opt,name=is_absolute,json=isAbsolute,proto3" json:"is_absolute,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceCriteria) Reset() {
	*x = PerformanceCriteria{}
	mi := &file_motivation_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceCriteria) ProtoMessage() {}

func (x *PerformanceCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceCriteria.ProtoReflect.Descriptor instead.
func (*PerformanceCriteria) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{8}
}

func (x *PerformanceCriteria) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PerformanceCriteria) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *PerformanceCriteria) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *PerformanceCriteria) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *PerformanceCriteria) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PerformanceCriteria) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PerformanceCriteria) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PerformanceCriteria) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *PerformanceCriteria) GetIsAbsolute() bool {
	if x != nil {
		return x.IsAbsolute
	}
	return false
}

func (x *PerformanceCriteria) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

type PerformanceCriteriaID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceCriteriaID) Reset() {
	*x = PerformanceCriteriaID{}
	mi := &file_motivation_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceCriteriaID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceCriteriaID) ProtoMessage() {}

func (x *PerformanceCriteriaID) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceCriteriaID.ProtoReflect.Descriptor instead.
func (*PerformanceCriteriaID) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{9}
}

func (x *PerformanceCriteriaID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PerformanceCriteriaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PerformanceCriteria `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceCriteriaList) Reset() {
	*x = PerformanceCriteriaList{}
	mi := &file_motivation_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceCriteriaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceCriteriaList) ProtoMessage() {}

func (x *PerformanceCriteriaList) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceCriteriaList.ProtoReflect.Descriptor instead.
func (*PerformanceCriteriaList) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{10}
}

func (x *PerformanceCriteriaList) GetItems() []*PerformanceCriteria {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListPerformanceCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	DepartmentId  *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	UserId        *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPerformanceCriteriaRequest) Reset() {
	*x = ListPerformanceCriteriaRequest{}
	mi := &file_motivation_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPerformanceCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPerformanceCriteriaRequest) ProtoMessage() {}

func (x *ListPerformanceCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPerformanceCriteriaRequest.ProtoReflect.Descriptor instead.
func (*ListPerformanceCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListPerformanceCriteriaRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListPerformanceCriteriaRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ListPerformanceCriteriaRequest) GetDepartmentId() *wrapperspb.Int64Value {
	if x != nil {
		return x.DepartmentId
	}
	return nil
}

func (x *ListPerformanceCriteriaRequest) GetUserId() *wrapperspb.Int64Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

type CreatePerformanceCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	DepartmentId  *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	UserId        *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	IsAbsolute    bool                   `protobuf:"varint,8,opt,name=is_absolute,json=isAbsolute,proto3" json:"is_absolute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePerformanceCriteriaRequest) Reset() {
	*x = CreatePerformanceCriteriaRequest{}
	mi := &file_motivation_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePerformanceCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePerformanceCriteriaRequest) ProtoMessage() {}

func (x *CreatePerformanceCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePerformanceCriteriaRequest.ProtoReflect.Descriptor instead.
func (*CreatePerformanceCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePerformanceCriteriaRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreatePerformanceCriteriaRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CreatePerformanceCriteriaRequest) GetDepartmentId() *wrapperspb.Int64Value {
	if x != nil {
		return x.DepartmentId
	}
	return nil
}

func (x *CreatePerformanceCriteriaRequest) GetUserId() *wrapperspb.Int64Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreatePerformanceCriteriaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePerformanceCriteriaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePerformanceCriteriaRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *CreatePerformanceCriteriaRequest) GetIsAbsolute() bool {
	if x != nil {
		return x.IsAbsolute
	}
	return false
}

type UpdatePerformanceCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	IsAbsolute    bool                   `protobuf:"varint,5,opt,name=is_absolute,json=isAbsolute,proto3" json:"is_absolute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePerformanceCriteriaRequest) Reset() {
	*x = UpdatePerformanceCriteriaRequest{}
	mi := &file_motivation_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePerformanceCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePerformanceCriteriaRequest) ProtoMessage() {}

func (x *UpdatePerformanceCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePerformanceCriteriaRequest.ProtoReflect.Descriptor instead.
func (*UpdatePerformanceCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePerformanceCriteriaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePerformanceCriteriaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePerformanceCriteriaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePerformanceCriteriaRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *UpdatePerformanceCriteriaRequest) GetIsAbsolute() bool {
	if x != nil {
		return x.IsAbsolute
	}
	return false
}

type UserPerformance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StaffId       int64                  `protobuf:"varint,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	CriteriaId    int64                  `protobuf:"varint,4,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	EarnedScore   int32                  `protobuf:"varint,5,opt,name=earned_score,json=earnedScore,proto3" json:"earned_score,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	EvaluatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	EvaluatedBy   int64                  `protobuf:"varint,8,opt,name=evaluated_by,json=evaluatedBy,proto3" json:"evaluated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPerformance) Reset() {
	*x = UserPerformance{}
	mi := &file_motivation_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPerformance) ProtoMessage() {}

func (x *UserPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPerformance.ProtoReflect.Descriptor instead.
func (*UserPerformance) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{14}
}

func (x *UserPerformance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPerformance) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPerformance) GetStaffId() int64 {
	if x != nil {
		return x.StaffId
	}
	return 0
}

func (x *UserPerformance) GetCriteriaId() int64 {
	if x != nil {
		return x.CriteriaId
	}
	return 0
}

func (x *UserPerformance) GetEarnedScore() int32 {
	if x != nil {
		return x.EarnedScore
	}
	return 0
}

func (x *UserPerformance) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UserPerformance) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *UserPerformance) GetEvaluatedBy() int64 {
	if x != nil {
		return x.EvaluatedBy
	}
	return 0
}

type UserPerformanceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserPerformance     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPerformanceList) Reset() {
	*x = UserPerformanceList{}
	mi := &file_motivation_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPerformanceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPerformanceList) ProtoMessage() {}

func (x *UserPerformanceList) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPerformanceList.ProtoReflect.Descriptor instead.
func (*UserPerformanceList) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{15}
}

func (x *UserPerformanceList) GetItems() []*UserPerformance {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpsertUserPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StaffId       *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	CriteriaId    int64                  `protobuf:"varint,3,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	EarnedScore   int32                  `protobuf:"varint,4,opt,name=earned_score,json=earnedScore,proto3" json:"earned_score,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserPerformanceRequest) Reset() {
	*x = UpsertUserPerformanceRequest{}
	mi := &file_motivation_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserPerformanceRequest) ProtoMessage() {}

func (x *UpsertUserPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserPerformanceRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpsertUserPerformanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpsertUserPerformanceRequest) GetStaffId() *wrapperspb.Int64Value {
	if x != nil {
		return x.StaffId
	}
	return nil
}

func (x *UpsertUserPerformanceRequest) GetCriteriaId() int64 {
	if x != nil {
		return x.CriteriaId
	}
	return 0
}

func (x *UpsertUserPerformanceRequest) GetEarnedScore() int32 {
	if x != nil {
		return x.EarnedScore
	}
	return 0
}

func (x *UpsertUserPerformanceRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ListUserPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPerformanceRequest) Reset() {
	*x = ListUserPerformanceRequest{}
	mi := &file_motivation_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPerformanceRequest) ProtoMessage() {}

func (x *ListUserPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPerformanceRequest.ProtoReflect.Descriptor instead.
func (*ListUserPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserPerformanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserPerformanceRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListUserPerformanceRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type CalculateUserPercentageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateUserPercentageRequest) Reset() {
	*x = CalculateUserPercentageRequest{}
	mi := &file_motivation_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateUserPercentageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateUserPercentageRequest) ProtoMessage() {}

func (x *CalculateUserPercentageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateUserPercentageRequest.ProtoReflect.Descriptor instead.
func (*CalculateUserPercentageRequest) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{18}
}

func (x *CalculateUserPercentageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CalculateUserPercentageRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CalculateUserPercentageRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type UserPercentage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BasePercent     float64                `protobuf:"fixed64,1,opt,name=base_percent,json=basePercent,proto3" json:"base_percent,omitempty"`
	AbsolutePercent float64                `protobuf:"fixed64,2,opt,name=absolute_percent,json=absolutePercent,proto3" json:"absolute_percent,omitempty"`
	TotalPercent    float64                `protobuf:"fixed64,3,opt,name=total_percent,json=totalPercent,proto3" json:"total_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserPercentage) Reset() {
	*x = UserPercentage{}
	mi := &file_motivation_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPercentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPercentage) ProtoMessage() {}

func (x *UserPercentage) ProtoReflect() protoreflect.Message {
	mi := &file_motivation_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPercentage.ProtoReflect.Descriptor instead.
func (*UserPercentage) Descriptor() ([]byte, []int) {
	return file_motivation_service_proto_rawDescGZIP(), []int{19}
}

func (x *UserPercentage) GetBasePercent() float64 {
	if x != nil {
		return x.BasePercent
	}
	return 0
}

func (x *UserPercentage) GetAbsolutePercent() float64 {
	if x != nil {
		return x.AbsolutePercent
	}
	return 0
}

func (x *UserPercentage) GetTotalPercent() float64 {
	if x != nil {
		return x.TotalPercent
	}
	return 0
}

var File_motivation_service_proto protoreflect.FileDescriptor

const file_motivation_service_proto_rawDesc = "" +
	"\n" +
	"\x18motivation/service.proto\x12\n" +
	"motivation\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x82\x02\n" +
	"\fBaseCriteria\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\x129\n" +
	"\n" +
	"valid_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\x03R\tupdatedBy\"B\n" +
	"\x10BaseCriteriaList\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.motivation.BaseCriteriaR\x05items\"\xe0\x01\n" +
	"\x19CreateBaseCriteriaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x03 \x01(\x05R\bmaxScore\x129\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\"\xf0\x01\n" +
	"\x19UpdateBaseCriteriaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\x129\n" +
	"\n" +
	"valid_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\"\xf7\x01\n" +
	"\x11PerformancePeriod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\x03R\tupdatedBy\"%\n" +
	"\x13PerformancePeriodID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"M\n" +
	"\x16PerformancePeriodsList\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.motivation.PerformancePeriodR\x05items\"\xd5\x01\n" +
	"\x1eUpsertPerformancePeriodRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\"\xa0\x02\n" +
	"\x13PerformanceCriteria\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\x03R\fdepartmentId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\b \x01(\x05R\bmaxScore\x12\x1f\n" +
	"\vis_absolute\x18\t \x01(\bR\n" +
	"isAbsolute\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\x03R\tupdatedBy\"'\n" +
	"\x15PerformanceCriteriaID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"P\n" +
	"\x17PerformanceCriteriaList\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.motivation.PerformanceCriteriaR\x05items\"\xc2\x01\n" +
	"\x1eListPerformanceCriteriaRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12@\n" +
	"\rdepartment_id\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\fdepartmentId\x124\n" +
	"\auser_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06userId\"\xb8\x02\n" +
	" CreatePerformanceCriteriaRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12@\n" +
	"\rdepartment_id\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\fdepartmentId\x124\n" +
	"\auser_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06userId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\a \x01(\x05R\bmaxScore\x12\x1f\n" +
	"\vis_absolute\x18\b \x01(\bR\n" +
	"isAbsolute\"\xa6\x01\n" +
	" UpdatePerformanceCriteriaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\x12\x1f\n" +
	"\vis_absolute\x18\x05 \x01(\bR\n" +
	"isAbsolute\"\x95\x02\n" +
	"\x0fUserPerformance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bstaff_id\x18\x03 \x01(\x03R\astaffId\x12\x1f\n" +
	"\vcriteria_id\x18\x04 \x01(\x03R\n" +
	"criteriaId\x12!\n" +
	"\fearned_score\x18\x05 \x01(\x05R\vearnedScore\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12=\n" +
	"\fevaluated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12!\n" +
	"\fevaluated_by\x18\b \x01(\x03R\vevaluatedBy\"H\n" +
	"\x13UserPerformanceList\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.motivation.UserPerformanceR\x05items\"\xcd\x01\n" +
	"\x1cUpsertUserPerformanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x126\n" +
	"\bstaff_id\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\astaffId\x12\x1f\n" +
	"\vcriteria_id\x18\x03 \x01(\x03R\n" +
	"criteriaId\x12!\n" +
	"\fearned_score\x18\x04 \x01(\x05R\vearnedScore\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"_\n" +
	"\x1aListUserPerformanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"c\n" +
	"\x1eCalculateUserPercentageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"\x83\x01\n" +
	"\x0eUserPercentage\x12!\n" +
	"\fbase_percent\x18\x01 \x01(\x01R\vbasePercent\x12)\n" +
	"\x10absolute_percent\x18\x02 \x01(\x01R\x0fabsolutePercent\x12#\n" +
	"\rtotal_percent\x18\x03 \x01(\x01R\ftotalPercent2\xa7\b\n" +
	"\n" +
	"Motivation\x12H\n" +
	"\x10ListBaseCriteria\x12\x16.google.protobuf.Empty\x1a\x1c.motivation.BaseCriteriaList\x12U\n" +
	"\x12CreateBaseCriteria\x12%.motivation.CreateBaseCriteriaRequest\x1a\x18.motivation.BaseCriteria\x12U\n" +
	"\x12UpdateBaseCriteria\x12%.motivation.UpdateBaseCriteriaRequest\x1a\x18.motivation.BaseCriteria\x12T\n" +
	"\x16ListPerformancePeriods\x12\x16.google.protobuf.Empty\x1a\".motivation.PerformancePeriodsList\x12d\n" +
	"\x17UpsertPerformancePeriod\x12*.motivation.UpsertPerformancePeriodRequest\x1a\x1d.motivation.PerformancePeriod\x12j\n" +
	"\x17ListPerformanceCriteria\x12*.motivation.ListPerformanceCriteriaRequest\x1a#.motivation.PerformanceCriteriaList\x12j\n" +
	"\x19CreatePerformanceCriteria\x12,.motivation.CreatePerformanceCriteriaRequest\x1a\x1f.motivation.PerformanceCriteria\x12j\n" +
	"\x19UpdatePerformanceCriteria\x12,.motivation.UpdatePerformanceCriteriaRequest\x1a\x1f.motivation.PerformanceCriteria\x12^\n" +
	"\x15UpsertUserPerformance\x12(.motivation.UpsertUserPerformanceRequest\x1a\x1b.motivation.UserPerformance\x12^\n" +
	"\x13ListUserPerformance\x12&.motivation.ListUserPerformanceRequest\x1a\x1f.motivation.UserPerformanceList\x12a\n" +
	"\x17CalculateUserPercentage\x12*.motivation.CalculateUserPercentageRequest\x1a\x1a.motivation.UserPercentageB3Z1github.com/SOTBI-LLC/sotbi.lib/pkg/api/motivationb\x06proto3"

var (
	file_motivation_service_proto_rawDescOnce sync.Once
	file_motivation_service_proto_rawDescData []byte
)

func file_motivation_service_proto_rawDescGZIP() []byte {
	file_motivation_service_proto_rawDescOnce.Do(func() {
		file_motivation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_motivation_service_proto_rawDesc), len(file_motivation_service_proto_rawDesc)))
	})
	return file_motivation_service_proto_rawDescData
}

var file_motivation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_motivation_service_proto_goTypes = []any{
	(*BaseCriteria)(nil),                     // 0: motivation.BaseCriteria
	(*BaseCriteriaList)(nil),                 // 1: motivation.BaseCriteriaList
	(*CreateBaseCriteriaRequest)(nil),        // 2: motivation.CreateBaseCriteriaRequest
	(*UpdateBaseCriteriaRequest)(nil),        // 3: motivation.UpdateBaseCriteriaRequest
	(*PerformancePeriod)(nil),                // 4: motivation.PerformancePeriod
	(*PerformancePeriodID)(nil),              // 5: motivation.PerformancePeriodID
	(*PerformancePeriodsList)(nil),           // 6: motivation.PerformancePeriodsList
	(*UpsertPerformancePeriodRequest)(nil),   // 7: motivation.UpsertPerformancePeriodRequest
	(*PerformanceCriteria)(nil),              // 8: motivation.PerformanceCriteria
	(*PerformanceCriteriaID)(nil),            // 9: motivation.PerformanceCriteriaID
	(*PerformanceCriteriaList)(nil),          // 10: motivation.PerformanceCriteriaList
	(*ListPerformanceCriteriaRequest)(nil),   // 11: motivation.ListPerformanceCriteriaRequest
	(*CreatePerformanceCriteriaRequest)(nil), // 12: motivation.CreatePerformanceCriteriaRequest
	(*UpdatePerformanceCriteriaRequest)(nil), // 13: motivation.UpdatePerformanceCriteriaRequest
	(*UserPerformance)(nil),                  // 14: motivation.UserPerformance
	(*UserPerformanceList)(nil),              // 15: motivation.UserPerformanceList
	(*UpsertUserPerformanceRequest)(nil),     // 16: motivation.UpsertUserPerformanceRequest
	(*ListUserPerformanceRequest)(nil),       // 17: motivation.ListUserPerformanceRequest
	(*CalculateUserPercentageRequest)(nil),   // 18: motivation.CalculateUserPercentageRequest
	(*UserPercentage)(nil),                   // 19: motivation.UserPercentage
	(*timestamppb.Timestamp)(nil),            // 20: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil),            // 21: google.protobuf.Int64Value
	(*emptypb.Empty)(nil),                    // 22: google.protobuf.Empty
}
var file_motivation_service_proto_depIdxs = []int32{
	20, // 0: motivation.BaseCriteria.valid_from:type_name -> google.protobuf.Timestamp
	20, // 1: motivation.BaseCriteria.valid_to:type_name -> google.protobuf.Timestamp
	0,  // 2: motivation.BaseCriteriaList.items:type_name -> motivation.BaseCriteria
	20, // 3: motivation.CreateBaseCriteriaRequest.valid_from:type_name -> google.protobuf.Timestamp
	20, // 4: motivation.CreateBaseCriteriaRequest.valid_to:type_name -> google.protobuf.Timestamp
	20, // 5: motivation.UpdateBaseCriteriaRequest.valid_from:type_name -> google.protobuf.Timestamp
	20, // 6: motivation.UpdateBaseCriteriaRequest.valid_to:type_name -> google.protobuf.Timestamp
	20, // 7: motivation.PerformancePeriod.starts_at:type_name -> google.protobuf.Timestamp
	20, // 8: motivation.PerformancePeriod.ends_at:type_name -> google.protobuf.Timestamp
	4,  // 9: motivation.PerformancePeriodsList.items:type_name -> motivation.PerformancePeriod
	20, // 10: motivation.UpsertPerformancePeriodRequest.starts_at:type_name -> google.protobuf.Timestamp
	20, // 11: motivation.UpsertPerformancePeriodRequest.ends_at:type_name -> google.protobuf.Timestamp
	8,  // 12: motivation.PerformanceCriteriaList.items:type_name -> motivation.PerformanceCriteria
	21, // 13: motivation.ListPerformanceCriteriaRequest.department_id:type_name -> google.protobuf.Int64Value
	21, // 14: motivation.ListPerformanceCriteriaRequest.user_id:type_name -> google.protobuf.Int64Value
	21, // 15: motivation.CreatePerformanceCriteriaRequest.department_id:type_name -> google.protobuf.Int64Value
	21, // 16: motivation.CreatePerformanceCriteriaRequest.user_id:type_name -> google.protobuf.Int64Value
	20, // 17: motivation.UserPerformance.evaluated_at:type_name -> google.protobuf.Timestamp
	14, // 18: motivation.UserPerformanceList.items:type_name -> motivation.UserPerformance
	21, // 19: motivation.UpsertUserPerformanceRequest.staff_id:type_name -> google.protobuf.Int64Value
	22, // 20: motivation.Motivation.ListBaseCriteria:input_type -> google.protobuf.Empty
	2,  // 21: motivation.Motivation.CreateBaseCriteria:input_type -> motivation.CreateBaseCriteriaRequest
	3,  // 22: motivation.Motivation.UpdateBaseCriteria:input_type -> motivation.UpdateBaseCriteriaRequest
	22, // 23: motivation.Motivation.ListPerformancePeriods:input_type -> google.protobuf.Empty
	7,  // 24: motivation.Motivation.UpsertPerformancePeriod:input_type -> motivation.UpsertPerformancePeriodRequest
	11, // 25: motivation.Motivation.ListPerformanceCriteria:input_type -> motivation.ListPerformanceCriteriaRequest
	12, // 26: motivation.Motivation.CreatePerformanceCriteria:input_type -> motivation.CreatePerformanceCriteriaRequest
	13, // 27: motivation.Motivation.UpdatePerformanceCriteria:input_type -> motivation.UpdatePerformanceCriteriaRequest
	16, // 28: motivation.Motivation.UpsertUserPerformance:input_type -> motivation.UpsertUserPerformanceRequest
	17, // 29: motivation.Motivation.ListUserPerformance:input_type -> motivation.ListUserPerformanceRequest
	18, // 30: motivation.Motivation.CalculateUserPercentage:input_type -> motivation.CalculateUserPercentageRequest
	1,  // 31: motivation.Motivation.ListBaseCriteria:output_type -> motivation.BaseCriteriaList
	0,  // 32: motivation.Motivation.CreateBaseCriteria:output_type -> motivation.BaseCriteria
	0,  // 33: motivation.Motivation.UpdateBaseCriteria:output_type -> motivation.BaseCriteria
	6,  // 34: motivation.Motivation.ListPerformancePeriods:output_type -> motivation.PerformancePeriodsList
	4,  // 35: motivation.Motivation.UpsertPerformancePeriod:output_type -> motivation.PerformancePeriod
	10, // 36: motivation.Motivation.ListPerformanceCriteria:output_type -> motivation.PerformanceCriteriaList
	8,  // 37: motivation.Motivation.CreatePerformanceCriteria:output_type -> motivation.PerformanceCriteria
	8,  // 38: motivation.Motivation.UpdatePerformanceCriteria:output_type -> motivation.PerformanceCriteria
	14, // 39: motivation.Motivation.UpsertUserPerformance:output_type -> motivation.UserPerformance
	15, // 40: motivation.Motivation.ListUserPerformance:output_type -> motivation.UserPerformanceList
	19, // 41: motivation.Motivation.CalculateUserPercentage:output_type -> motivation.UserPercentage
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_motivation_service_proto_init() }
func file_motivation_service_proto_init() {
	if File_motivation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_motivation_service_proto_rawDesc), len(file_motivation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_motivation_service_proto_goTypes,
		DependencyIndexes: file_motivation_service_proto_depIdxs,
		MessageInfos:      file_motivation_service_proto_msgTypes,
	}.Build()
	File_motivation_service_proto = out.File
	file_motivation_service_proto_goTypes = nil
	file_motivation_service_proto_depIdxs = nil
}
