// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: api/motivation/v1/service.proto

package motivationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PerformanceEvaluationService_CreateBaseCriteria_FullMethodName        = "/motivation.v1.PerformanceEvaluationService/CreateBaseCriteria"
	PerformanceEvaluationService_UpdateBaseCriteria_FullMethodName        = "/motivation.v1.PerformanceEvaluationService/UpdateBaseCriteria"
	PerformanceEvaluationService_GetBaseCriteria_FullMethodName           = "/motivation.v1.PerformanceEvaluationService/GetBaseCriteria"
	PerformanceEvaluationService_ListBaseCriteria_FullMethodName          = "/motivation.v1.PerformanceEvaluationService/ListBaseCriteria"
	PerformanceEvaluationService_GetCoefficientCap_FullMethodName         = "/motivation.v1.PerformanceEvaluationService/GetCoefficientCap"
	PerformanceEvaluationService_SetCoefficientCap_FullMethodName         = "/motivation.v1.PerformanceEvaluationService/SetCoefficientCap"
	PerformanceEvaluationService_OpenPeriod_FullMethodName                = "/motivation.v1.PerformanceEvaluationService/OpenPeriod"
	PerformanceEvaluationService_ReopenPeriod_FullMethodName              = "/motivation.v1.PerformanceEvaluationService/ReopenPeriod"
	PerformanceEvaluationService_GetPeriod_FullMethodName                 = "/motivation.v1.PerformanceEvaluationService/GetPeriod"
	PerformanceEvaluationService_ListPeriods_FullMethodName               = "/motivation.v1.PerformanceEvaluationService/ListPeriods"
	PerformanceEvaluationService_IncludeUser_FullMethodName               = "/motivation.v1.PerformanceEvaluationService/IncludeUser"
	PerformanceEvaluationService_SetCriterionScore_FullMethodName         = "/motivation.v1.PerformanceEvaluationService/SetCriterionScore"
	PerformanceEvaluationService_SetAdjustment_FullMethodName             = "/motivation.v1.PerformanceEvaluationService/SetAdjustment"
	PerformanceEvaluationService_GetPerformanceSheet_FullMethodName       = "/motivation.v1.PerformanceEvaluationService/GetPerformanceSheet"
	PerformanceEvaluationService_ListPerformanceSheets_FullMethodName     = "/motivation.v1.PerformanceEvaluationService/ListPerformanceSheets"
	PerformanceEvaluationService_StreamPerformanceSheets_FullMethodName   = "/motivation.v1.PerformanceEvaluationService/StreamPerformanceSheets"
	PerformanceEvaluationService_ListPayrollResults_FullMethodName        = "/motivation.v1.PerformanceEvaluationService/ListPayrollResults"
	PerformanceEvaluationService_StreamPayrollResults_FullMethodName      = "/motivation.v1.PerformanceEvaluationService/StreamPayrollResults"
	PerformanceEvaluationService_StartClosePeriod_FullMethodName          = "/motivation.v1.PerformanceEvaluationService/StartClosePeriod"
	PerformanceEvaluationService_GetClosePeriodOperation_FullMethodName   = "/motivation.v1.PerformanceEvaluationService/GetClosePeriodOperation"
	PerformanceEvaluationService_WatchClosePeriodOperation_FullMethodName = "/motivation.v1.PerformanceEvaluationService/WatchClosePeriodOperation"
)

// PerformanceEvaluationServiceClient is the client API for PerformanceEvaluationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PerformanceEvaluationService is the clean v1 boundary owned by Motivation.
//
// Motivation derives the authenticated UserID and roles from trusted gRPC
// metadata and remains the authorization authority even behind a gateway. A
// User can read their own sheets, a current manager can read and score current
// reports, an administrator manages catalog, cap, lifecycle and inclusion,
// and payroll can read results for Closed Periods only.
//
// Boundary validation maps to InvalidArgument with google.rpc.BadRequest
// details. Identity, authorization, absence, duplicate/idempotency conflict,
// lifecycle, transient, context and unexpected failures map respectively to
// Unauthenticated, PermissionDenied, NotFound, AlreadyExists,
// FailedPrecondition, Unavailable, Canceled/DeadlineExceeded and Internal.
//
// Every mutation requires a UUID idempotency_key. For at least 24 hours, the
// same method and payload returns its original terminal outcome without a
// second mutation; reuse with another method or payload returns AlreadyExists.
// Caller identity and audit time are never accepted in mutation bodies.
type PerformanceEvaluationServiceClient interface {
	CreateBaseCriteria(ctx context.Context, in *CreateBaseCriteriaRequest, opts ...grpc.CallOption) (*CreateBaseCriteriaResponse, error)
	UpdateBaseCriteria(ctx context.Context, in *UpdateBaseCriteriaRequest, opts ...grpc.CallOption) (*UpdateBaseCriteriaResponse, error)
	GetBaseCriteria(ctx context.Context, in *GetBaseCriteriaRequest, opts ...grpc.CallOption) (*GetBaseCriteriaResponse, error)
	ListBaseCriteria(ctx context.Context, in *ListBaseCriteriaRequest, opts ...grpc.CallOption) (*ListBaseCriteriaResponse, error)
	GetCoefficientCap(ctx context.Context, in *GetCoefficientCapRequest, opts ...grpc.CallOption) (*GetCoefficientCapResponse, error)
	SetCoefficientCap(ctx context.Context, in *SetCoefficientCapRequest, opts ...grpc.CallOption) (*SetCoefficientCapResponse, error)
	OpenPeriod(ctx context.Context, in *OpenPeriodRequest, opts ...grpc.CallOption) (*OpenPeriodResponse, error)
	ReopenPeriod(ctx context.Context, in *ReopenPeriodRequest, opts ...grpc.CallOption) (*ReopenPeriodResponse, error)
	GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error)
	ListPeriods(ctx context.Context, in *ListPeriodsRequest, opts ...grpc.CallOption) (*ListPeriodsResponse, error)
	IncludeUser(ctx context.Context, in *IncludeUserRequest, opts ...grpc.CallOption) (*IncludeUserResponse, error)
	SetCriterionScore(ctx context.Context, in *SetCriterionScoreRequest, opts ...grpc.CallOption) (*SetCriterionScoreResponse, error)
	SetAdjustment(ctx context.Context, in *SetAdjustmentRequest, opts ...grpc.CallOption) (*SetAdjustmentResponse, error)
	GetPerformanceSheet(ctx context.Context, in *GetPerformanceSheetRequest, opts ...grpc.CallOption) (*GetPerformanceSheetResponse, error)
	ListPerformanceSheets(ctx context.Context, in *ListPerformanceSheetsRequest, opts ...grpc.CallOption) (*ListPerformanceSheetsResponse, error)
	// StreamPerformanceSheets is a finite point-in-time alternative to the
	// unary list. It preserves ascending UserID order and ends after the last
	// resource; it is not a live subscription.
	StreamPerformanceSheets(ctx context.Context, in *StreamPerformanceSheetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPerformanceSheetsResponse], error)
	ListPayrollResults(ctx context.Context, in *ListPayrollResultsRequest, opts ...grpc.CallOption) (*ListPayrollResultsResponse, error)
	// StreamPayrollResults is a finite Closed-Period snapshot in ascending
	// UserID order and ends after the last resource.
	StreamPayrollResults(ctx context.Context, in *StreamPayrollResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPayrollResultsResponse], error)
	// StartClosePeriod durably accepts work and makes the Period Closing before
	// returning. Closing blocks scoring, Adjustment, inclusion, Reopen and an
	// independent Close. The same key returns the same operation; another key
	// returns an active operation; Closed returns its latest successful
	// operation; a new key after failure or Reopen creates a new operation.
	// Success atomically leaves Closed, failure leaves Open with no partial
	// Close materialization. v1 exposes no cancellation.
	StartClosePeriod(ctx context.Context, in *StartClosePeriodRequest, opts ...grpc.CallOption) (*StartClosePeriodResponse, error)
	// GetClosePeriodOperation supports durable polling across process restarts.
	GetClosePeriodOperation(ctx context.Context, in *GetClosePeriodOperationRequest, opts ...grpc.CallOption) (*GetClosePeriodOperationResponse, error)
	// WatchClosePeriodOperation first sends the current durable state, then
	// later durable state/progress changes, and ends after a terminal message.
	// A Failed business operation is a normal terminal message; a stream error
	// represents a transport failure.
	WatchClosePeriodOperation(ctx context.Context, in *WatchClosePeriodOperationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchClosePeriodOperationResponse], error)
}

type performanceEvaluationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPerformanceEvaluationServiceClient(cc grpc.ClientConnInterface) PerformanceEvaluationServiceClient {
	return &performanceEvaluationServiceClient{cc}
}

func (c *performanceEvaluationServiceClient) CreateBaseCriteria(ctx context.Context, in *CreateBaseCriteriaRequest, opts ...grpc.CallOption) (*CreateBaseCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBaseCriteriaResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_CreateBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) UpdateBaseCriteria(ctx context.Context, in *UpdateBaseCriteriaRequest, opts ...grpc.CallOption) (*UpdateBaseCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBaseCriteriaResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_UpdateBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) GetBaseCriteria(ctx context.Context, in *GetBaseCriteriaRequest, opts ...grpc.CallOption) (*GetBaseCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaseCriteriaResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_GetBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) ListBaseCriteria(ctx context.Context, in *ListBaseCriteriaRequest, opts ...grpc.CallOption) (*ListBaseCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBaseCriteriaResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_ListBaseCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) GetCoefficientCap(ctx context.Context, in *GetCoefficientCapRequest, opts ...grpc.CallOption) (*GetCoefficientCapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoefficientCapResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_GetCoefficientCap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) SetCoefficientCap(ctx context.Context, in *SetCoefficientCapRequest, opts ...grpc.CallOption) (*SetCoefficientCapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCoefficientCapResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_SetCoefficientCap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) OpenPeriod(ctx context.Context, in *OpenPeriodRequest, opts ...grpc.CallOption) (*OpenPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenPeriodResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_OpenPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) ReopenPeriod(ctx context.Context, in *ReopenPeriodRequest, opts ...grpc.CallOption) (*ReopenPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReopenPeriodResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_ReopenPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeriodResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_GetPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) ListPeriods(ctx context.Context, in *ListPeriodsRequest, opts ...grpc.CallOption) (*ListPeriodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeriodsResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_ListPeriods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) IncludeUser(ctx context.Context, in *IncludeUserRequest, opts ...grpc.CallOption) (*IncludeUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncludeUserResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_IncludeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) SetCriterionScore(ctx context.Context, in *SetCriterionScoreRequest, opts ...grpc.CallOption) (*SetCriterionScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCriterionScoreResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_SetCriterionScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) SetAdjustment(ctx context.Context, in *SetAdjustmentRequest, opts ...grpc.CallOption) (*SetAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdjustmentResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_SetAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) GetPerformanceSheet(ctx context.Context, in *GetPerformanceSheetRequest, opts ...grpc.CallOption) (*GetPerformanceSheetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPerformanceSheetResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_GetPerformanceSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) ListPerformanceSheets(ctx context.Context, in *ListPerformanceSheetsRequest, opts ...grpc.CallOption) (*ListPerformanceSheetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPerformanceSheetsResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_ListPerformanceSheets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) StreamPerformanceSheets(ctx context.Context, in *StreamPerformanceSheetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPerformanceSheetsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PerformanceEvaluationService_ServiceDesc.Streams[0], PerformanceEvaluationService_StreamPerformanceSheets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPerformanceSheetsRequest, StreamPerformanceSheetsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceEvaluationService_StreamPerformanceSheetsClient = grpc.ServerStreamingClient[StreamPerformanceSheetsResponse]

func (c *performanceEvaluationServiceClient) ListPayrollResults(ctx context.Context, in *ListPayrollResultsRequest, opts ...grpc.CallOption) (*ListPayrollResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPayrollResultsResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_ListPayrollResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) StreamPayrollResults(ctx context.Context, in *StreamPayrollResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPayrollResultsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PerformanceEvaluationService_ServiceDesc.Streams[1], PerformanceEvaluationService_StreamPayrollResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPayrollResultsRequest, StreamPayrollResultsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceEvaluationService_StreamPayrollResultsClient = grpc.ServerStreamingClient[StreamPayrollResultsResponse]

func (c *performanceEvaluationServiceClient) StartClosePeriod(ctx context.Context, in *StartClosePeriodRequest, opts ...grpc.CallOption) (*StartClosePeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartClosePeriodResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_StartClosePeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) GetClosePeriodOperation(ctx context.Context, in *GetClosePeriodOperationRequest, opts ...grpc.CallOption) (*GetClosePeriodOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClosePeriodOperationResponse)
	err := c.cc.Invoke(ctx, PerformanceEvaluationService_GetClosePeriodOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceEvaluationServiceClient) WatchClosePeriodOperation(ctx context.Context, in *WatchClosePeriodOperationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchClosePeriodOperationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PerformanceEvaluationService_ServiceDesc.Streams[2], PerformanceEvaluationService_WatchClosePeriodOperation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchClosePeriodOperationRequest, WatchClosePeriodOperationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceEvaluationService_WatchClosePeriodOperationClient = grpc.ServerStreamingClient[WatchClosePeriodOperationResponse]

// PerformanceEvaluationServiceServer is the server API for PerformanceEvaluationService service.
// All implementations must embed UnimplementedPerformanceEvaluationServiceServer
// for forward compatibility.
//
// PerformanceEvaluationService is the clean v1 boundary owned by Motivation.
//
// Motivation derives the authenticated UserID and roles from trusted gRPC
// metadata and remains the authorization authority even behind a gateway. A
// User can read their own sheets, a current manager can read and score current
// reports, an administrator manages catalog, cap, lifecycle and inclusion,
// and payroll can read results for Closed Periods only.
//
// Boundary validation maps to InvalidArgument with google.rpc.BadRequest
// details. Identity, authorization, absence, duplicate/idempotency conflict,
// lifecycle, transient, context and unexpected failures map respectively to
// Unauthenticated, PermissionDenied, NotFound, AlreadyExists,
// FailedPrecondition, Unavailable, Canceled/DeadlineExceeded and Internal.
//
// Every mutation requires a UUID idempotency_key. For at least 24 hours, the
// same method and payload returns its original terminal outcome without a
// second mutation; reuse with another method or payload returns AlreadyExists.
// Caller identity and audit time are never accepted in mutation bodies.
type PerformanceEvaluationServiceServer interface {
	CreateBaseCriteria(context.Context, *CreateBaseCriteriaRequest) (*CreateBaseCriteriaResponse, error)
	UpdateBaseCriteria(context.Context, *UpdateBaseCriteriaRequest) (*UpdateBaseCriteriaResponse, error)
	GetBaseCriteria(context.Context, *GetBaseCriteriaRequest) (*GetBaseCriteriaResponse, error)
	ListBaseCriteria(context.Context, *ListBaseCriteriaRequest) (*ListBaseCriteriaResponse, error)
	GetCoefficientCap(context.Context, *GetCoefficientCapRequest) (*GetCoefficientCapResponse, error)
	SetCoefficientCap(context.Context, *SetCoefficientCapRequest) (*SetCoefficientCapResponse, error)
	OpenPeriod(context.Context, *OpenPeriodRequest) (*OpenPeriodResponse, error)
	ReopenPeriod(context.Context, *ReopenPeriodRequest) (*ReopenPeriodResponse, error)
	GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error)
	ListPeriods(context.Context, *ListPeriodsRequest) (*ListPeriodsResponse, error)
	IncludeUser(context.Context, *IncludeUserRequest) (*IncludeUserResponse, error)
	SetCriterionScore(context.Context, *SetCriterionScoreRequest) (*SetCriterionScoreResponse, error)
	SetAdjustment(context.Context, *SetAdjustmentRequest) (*SetAdjustmentResponse, error)
	GetPerformanceSheet(context.Context, *GetPerformanceSheetRequest) (*GetPerformanceSheetResponse, error)
	ListPerformanceSheets(context.Context, *ListPerformanceSheetsRequest) (*ListPerformanceSheetsResponse, error)
	// StreamPerformanceSheets is a finite point-in-time alternative to the
	// unary list. It preserves ascending UserID order and ends after the last
	// resource; it is not a live subscription.
	StreamPerformanceSheets(*StreamPerformanceSheetsRequest, grpc.ServerStreamingServer[StreamPerformanceSheetsResponse]) error
	ListPayrollResults(context.Context, *ListPayrollResultsRequest) (*ListPayrollResultsResponse, error)
	// StreamPayrollResults is a finite Closed-Period snapshot in ascending
	// UserID order and ends after the last resource.
	StreamPayrollResults(*StreamPayrollResultsRequest, grpc.ServerStreamingServer[StreamPayrollResultsResponse]) error
	// StartClosePeriod durably accepts work and makes the Period Closing before
	// returning. Closing blocks scoring, Adjustment, inclusion, Reopen and an
	// independent Close. The same key returns the same operation; another key
	// returns an active operation; Closed returns its latest successful
	// operation; a new key after failure or Reopen creates a new operation.
	// Success atomically leaves Closed, failure leaves Open with no partial
	// Close materialization. v1 exposes no cancellation.
	StartClosePeriod(context.Context, *StartClosePeriodRequest) (*StartClosePeriodResponse, error)
	// GetClosePeriodOperation supports durable polling across process restarts.
	GetClosePeriodOperation(context.Context, *GetClosePeriodOperationRequest) (*GetClosePeriodOperationResponse, error)
	// WatchClosePeriodOperation first sends the current durable state, then
	// later durable state/progress changes, and ends after a terminal message.
	// A Failed business operation is a normal terminal message; a stream error
	// represents a transport failure.
	WatchClosePeriodOperation(*WatchClosePeriodOperationRequest, grpc.ServerStreamingServer[WatchClosePeriodOperationResponse]) error
	mustEmbedUnimplementedPerformanceEvaluationServiceServer()
}

// UnimplementedPerformanceEvaluationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerformanceEvaluationServiceServer struct{}

func (UnimplementedPerformanceEvaluationServiceServer) CreateBaseCriteria(context.Context, *CreateBaseCriteriaRequest) (*CreateBaseCriteriaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBaseCriteria not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) UpdateBaseCriteria(context.Context, *UpdateBaseCriteriaRequest) (*UpdateBaseCriteriaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBaseCriteria not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) GetBaseCriteria(context.Context, *GetBaseCriteriaRequest) (*GetBaseCriteriaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseCriteria not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) ListBaseCriteria(context.Context, *ListBaseCriteriaRequest) (*ListBaseCriteriaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBaseCriteria not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) GetCoefficientCap(context.Context, *GetCoefficientCapRequest) (*GetCoefficientCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoefficientCap not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) SetCoefficientCap(context.Context, *SetCoefficientCapRequest) (*SetCoefficientCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCoefficientCap not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) OpenPeriod(context.Context, *OpenPeriodRequest) (*OpenPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenPeriod not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) ReopenPeriod(context.Context, *ReopenPeriodRequest) (*ReopenPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReopenPeriod not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriod not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) ListPeriods(context.Context, *ListPeriodsRequest) (*ListPeriodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeriods not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) IncludeUser(context.Context, *IncludeUserRequest) (*IncludeUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncludeUser not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) SetCriterionScore(context.Context, *SetCriterionScoreRequest) (*SetCriterionScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCriterionScore not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) SetAdjustment(context.Context, *SetAdjustmentRequest) (*SetAdjustmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAdjustment not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) GetPerformanceSheet(context.Context, *GetPerformanceSheetRequest) (*GetPerformanceSheetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerformanceSheet not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) ListPerformanceSheets(context.Context, *ListPerformanceSheetsRequest) (*ListPerformanceSheetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPerformanceSheets not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) StreamPerformanceSheets(*StreamPerformanceSheetsRequest, grpc.ServerStreamingServer[StreamPerformanceSheetsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPerformanceSheets not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) ListPayrollResults(context.Context, *ListPayrollResultsRequest) (*ListPayrollResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPayrollResults not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) StreamPayrollResults(*StreamPayrollResultsRequest, grpc.ServerStreamingServer[StreamPayrollResultsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPayrollResults not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) StartClosePeriod(context.Context, *StartClosePeriodRequest) (*StartClosePeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClosePeriod not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) GetClosePeriodOperation(context.Context, *GetClosePeriodOperationRequest) (*GetClosePeriodOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClosePeriodOperation not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) WatchClosePeriodOperation(*WatchClosePeriodOperationRequest, grpc.ServerStreamingServer[WatchClosePeriodOperationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchClosePeriodOperation not implemented")
}
func (UnimplementedPerformanceEvaluationServiceServer) mustEmbedUnimplementedPerformanceEvaluationServiceServer() {
}
func (UnimplementedPerformanceEvaluationServiceServer) testEmbeddedByValue() {}

// UnsafePerformanceEvaluationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerformanceEvaluationServiceServer will
// result in compilation errors.
type UnsafePerformanceEvaluationServiceServer interface {
	mustEmbedUnimplementedPerformanceEvaluationServiceServer()
}

func RegisterPerformanceEvaluationServiceServer(s grpc.ServiceRegistrar, srv PerformanceEvaluationServiceServer) {
	// If the following call pancis, it indicates UnimplementedPerformanceEvaluationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PerformanceEvaluationService_ServiceDesc, srv)
}

func _PerformanceEvaluationService_CreateBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBaseCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).CreateBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_CreateBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).CreateBaseCriteria(ctx, req.(*CreateBaseCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_UpdateBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBaseCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).UpdateBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_UpdateBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).UpdateBaseCriteria(ctx, req.(*UpdateBaseCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_GetBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).GetBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_GetBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).GetBaseCriteria(ctx, req.(*GetBaseCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_ListBaseCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBaseCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).ListBaseCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_ListBaseCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).ListBaseCriteria(ctx, req.(*ListBaseCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_GetCoefficientCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoefficientCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).GetCoefficientCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_GetCoefficientCap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).GetCoefficientCap(ctx, req.(*GetCoefficientCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_SetCoefficientCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCoefficientCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).SetCoefficientCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_SetCoefficientCap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).SetCoefficientCap(ctx, req.(*SetCoefficientCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_OpenPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).OpenPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_OpenPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).OpenPeriod(ctx, req.(*OpenPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_ReopenPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReopenPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).ReopenPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_ReopenPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).ReopenPeriod(ctx, req.(*ReopenPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_GetPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).GetPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_GetPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).GetPeriod(ctx, req.(*GetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_ListPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeriodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).ListPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_ListPeriods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).ListPeriods(ctx, req.(*ListPeriodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_IncludeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncludeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).IncludeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_IncludeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).IncludeUser(ctx, req.(*IncludeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_SetCriterionScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCriterionScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).SetCriterionScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_SetCriterionScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).SetCriterionScore(ctx, req.(*SetCriterionScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_SetAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).SetAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_SetAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).SetAdjustment(ctx, req.(*SetAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_GetPerformanceSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceSheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).GetPerformanceSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_GetPerformanceSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).GetPerformanceSheet(ctx, req.(*GetPerformanceSheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_ListPerformanceSheets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPerformanceSheetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).ListPerformanceSheets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_ListPerformanceSheets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).ListPerformanceSheets(ctx, req.(*ListPerformanceSheetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_StreamPerformanceSheets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPerformanceSheetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PerformanceEvaluationServiceServer).StreamPerformanceSheets(m, &grpc.GenericServerStream[StreamPerformanceSheetsRequest, StreamPerformanceSheetsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceEvaluationService_StreamPerformanceSheetsServer = grpc.ServerStreamingServer[StreamPerformanceSheetsResponse]

func _PerformanceEvaluationService_ListPayrollResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPayrollResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).ListPayrollResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_ListPayrollResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).ListPayrollResults(ctx, req.(*ListPayrollResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_StreamPayrollResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPayrollResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PerformanceEvaluationServiceServer).StreamPayrollResults(m, &grpc.GenericServerStream[StreamPayrollResultsRequest, StreamPayrollResultsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceEvaluationService_StreamPayrollResultsServer = grpc.ServerStreamingServer[StreamPayrollResultsResponse]

func _PerformanceEvaluationService_StartClosePeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClosePeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).StartClosePeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_StartClosePeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).StartClosePeriod(ctx, req.(*StartClosePeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_GetClosePeriodOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClosePeriodOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceEvaluationServiceServer).GetClosePeriodOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceEvaluationService_GetClosePeriodOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceEvaluationServiceServer).GetClosePeriodOperation(ctx, req.(*GetClosePeriodOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceEvaluationService_WatchClosePeriodOperation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchClosePeriodOperationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PerformanceEvaluationServiceServer).WatchClosePeriodOperation(m, &grpc.GenericServerStream[WatchClosePeriodOperationRequest, WatchClosePeriodOperationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PerformanceEvaluationService_WatchClosePeriodOperationServer = grpc.ServerStreamingServer[WatchClosePeriodOperationResponse]

// PerformanceEvaluationService_ServiceDesc is the grpc.ServiceDesc for PerformanceEvaluationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerformanceEvaluationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "motivation.v1.PerformanceEvaluationService",
	HandlerType: (*PerformanceEvaluationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBaseCriteria",
			Handler:    _PerformanceEvaluationService_CreateBaseCriteria_Handler,
		},
		{
			MethodName: "UpdateBaseCriteria",
			Handler:    _PerformanceEvaluationService_UpdateBaseCriteria_Handler,
		},
		{
			MethodName: "GetBaseCriteria",
			Handler:    _PerformanceEvaluationService_GetBaseCriteria_Handler,
		},
		{
			MethodName: "ListBaseCriteria",
			Handler:    _PerformanceEvaluationService_ListBaseCriteria_Handler,
		},
		{
			MethodName: "GetCoefficientCap",
			Handler:    _PerformanceEvaluationService_GetCoefficientCap_Handler,
		},
		{
			MethodName: "SetCoefficientCap",
			Handler:    _PerformanceEvaluationService_SetCoefficientCap_Handler,
		},
		{
			MethodName: "OpenPeriod",
			Handler:    _PerformanceEvaluationService_OpenPeriod_Handler,
		},
		{
			MethodName: "ReopenPeriod",
			Handler:    _PerformanceEvaluationService_ReopenPeriod_Handler,
		},
		{
			MethodName: "GetPeriod",
			Handler:    _PerformanceEvaluationService_GetPeriod_Handler,
		},
		{
			MethodName: "ListPeriods",
			Handler:    _PerformanceEvaluationService_ListPeriods_Handler,
		},
		{
			MethodName: "IncludeUser",
			Handler:    _PerformanceEvaluationService_IncludeUser_Handler,
		},
		{
			MethodName: "SetCriterionScore",
			Handler:    _PerformanceEvaluationService_SetCriterionScore_Handler,
		},
		{
			MethodName: "SetAdjustment",
			Handler:    _PerformanceEvaluationService_SetAdjustment_Handler,
		},
		{
			MethodName: "GetPerformanceSheet",
			Handler:    _PerformanceEvaluationService_GetPerformanceSheet_Handler,
		},
		{
			MethodName: "ListPerformanceSheets",
			Handler:    _PerformanceEvaluationService_ListPerformanceSheets_Handler,
		},
		{
			MethodName: "ListPayrollResults",
			Handler:    _PerformanceEvaluationService_ListPayrollResults_Handler,
		},
		{
			MethodName: "StartClosePeriod",
			Handler:    _PerformanceEvaluationService_StartClosePeriod_Handler,
		},
		{
			MethodName: "GetClosePeriodOperation",
			Handler:    _PerformanceEvaluationService_GetClosePeriodOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPerformanceSheets",
			Handler:       _PerformanceEvaluationService_StreamPerformanceSheets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPayrollResults",
			Handler:       _PerformanceEvaluationService_StreamPayrollResults_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchClosePeriodOperation",
			Handler:       _PerformanceEvaluationService_WatchClosePeriodOperation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/motivation/v1/service.proto",
}
