// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.32.1
// source: counterparty/common.proto

package counterparty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CounterpartyID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartyID) Reset() {
	*x = CounterpartyID{}
	mi := &file_counterparty_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartyID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartyID) ProtoMessage() {}

func (x *CounterpartyID) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartyID.ProtoReflect.Descriptor instead.
func (*CounterpartyID) Descriptor() ([]byte, []int) {
	return file_counterparty_common_proto_rawDescGZIP(), []int{0}
}

func (x *CounterpartyID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_counterparty_common_proto protoreflect.FileDescriptor

var file_counterparty_common_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x4f, 0x54, 0x42, 0x49, 0x2d,
	0x4c, 0x4c, 0x43, 0x2f, 0x73, 0x6f, 0x74, 0x62, 0x69, 0x2e, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_counterparty_common_proto_rawDescOnce sync.Once
	file_counterparty_common_proto_rawDescData []byte
)

func file_counterparty_common_proto_rawDescGZIP() []byte {
	file_counterparty_common_proto_rawDescOnce.Do(func() {
		file_counterparty_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_counterparty_common_proto_rawDesc), len(file_counterparty_common_proto_rawDesc)))
	})
	return file_counterparty_common_proto_rawDescData
}

var file_counterparty_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_counterparty_common_proto_goTypes = []any{
	(*CounterpartyID)(nil), // 0: counterparty.CounterpartyID
}
var file_counterparty_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_counterparty_common_proto_init() }
func file_counterparty_common_proto_init() {
	if File_counterparty_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_counterparty_common_proto_rawDesc), len(file_counterparty_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_counterparty_common_proto_goTypes,
		DependencyIndexes: file_counterparty_common_proto_depIdxs,
		MessageInfos:      file_counterparty_common_proto_msgTypes,
	}.Build()
	File_counterparty_common_proto = out.File
	file_counterparty_common_proto_goTypes = nil
	file_counterparty_common_proto_depIdxs = nil
}
