// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: counterparty/employee.proto

package counterparty

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Employees     []*Employee            `protobuf:"bytes,10,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeesResponse) Reset() {
	*x = EmployeesResponse{}
	mi := &file_counterparty_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeesResponse) ProtoMessage() {}

func (x *EmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeesResponse.ProtoReflect.Descriptor instead.
func (*EmployeesResponse) Descriptor() ([]byte, []int) {
	return file_counterparty_employee_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeesResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

// Работник
type Employee struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int64                  `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	CounterpartyID int64                  `protobuf:"varint,3,opt,name=CounterpartyID,json=counterparty_id,proto3" json:"CounterpartyID,omitempty"` // ID контрагента
	Position       string                 `protobuf:"bytes,6,opt,name=Position,json=position,proto3" json:"Position,omitempty"`                     // Должность
	PositionType   string                 `protobuf:"bytes,9,opt,name=PositionType,json=position_type,proto3" json:"PositionType,omitempty"`        // Тип должности (Основное/По совместительству)
	ContourType    string                 `protobuf:"bytes,12,opt,name=ContourType,json=contour_type,proto3" json:"ContourType,omitempty"`          // Тип контура (Внутренний/Внешний)
	Start          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=Start,json=start,proto3" json:"Start,omitempty"`                             // Дата начала работы
	Stop           *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=Stop,json=stop,proto3,oneof" json:"Stop,omitempty"`                          // Дата окончания работы
	UserID         *int64                 `protobuf:"varint,21,opt,name=UserID,json=user_id,proto3,oneof" json:"UserID,omitempty"`                  // ID пользователя
	UserName       *string                `protobuf:"bytes,24,opt,name=UserName,json=user_name,proto3,oneof" json:"UserName,omitempty"`             // Имя пользователя
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=CreatedAt,json=created_at,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=UpdatedAt,json=updated_at,proto3" json:"UpdatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_counterparty_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_counterparty_employee_proto_rawDescGZIP(), []int{1}
}

func (x *Employee) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Employee) GetCounterpartyID() int64 {
	if x != nil {
		return x.CounterpartyID
	}
	return 0
}

func (x *Employee) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Employee) GetPositionType() string {
	if x != nil {
		return x.PositionType
	}
	return ""
}

func (x *Employee) GetContourType() string {
	if x != nil {
		return x.ContourType
	}
	return ""
}

func (x *Employee) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Employee) GetStop() *timestamppb.Timestamp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *Employee) GetUserID() int64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *Employee) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *Employee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Employee) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=Position,json=position,proto3" json:"Position,omitempty"`
	PositionType  string                 `protobuf:"bytes,5,opt,name=PositionType,json=position_type,proto3" json:"PositionType,omitempty"`
	ContourType   string                 `protobuf:"bytes,7,opt,name=ContourType,json=contour_type,proto3" json:"ContourType,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=Start,json=start,proto3" json:"Start,omitempty"`
	Stop          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=Stop,json=stop,proto3,oneof" json:"Stop,omitempty"`
	UserID        *int64                 `protobuf:"varint,13,opt,name=UserID,json=user_id,proto3,oneof" json:"UserID,omitempty"`
	UserName      *string                `protobuf:"bytes,15,opt,name=UserName,json=user_name,proto3,oneof" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEmployeeRequest) Reset() {
	*x = AddEmployeeRequest{}
	mi := &file_counterparty_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeRequest) ProtoMessage() {}

func (x *AddEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeRequest.ProtoReflect.Descriptor instead.
func (*AddEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_counterparty_employee_proto_rawDescGZIP(), []int{2}
}

func (x *AddEmployeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddEmployeeRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *AddEmployeeRequest) GetPositionType() string {
	if x != nil {
		return x.PositionType
	}
	return ""
}

func (x *AddEmployeeRequest) GetContourType() string {
	if x != nil {
		return x.ContourType
	}
	return ""
}

func (x *AddEmployeeRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AddEmployeeRequest) GetStop() *timestamppb.Timestamp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *AddEmployeeRequest) GetUserID() int64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *AddEmployeeRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

type UpdateEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Employees     []*Employee            `protobuf:"bytes,10,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeesRequest) Reset() {
	*x = UpdateEmployeesRequest{}
	mi := &file_counterparty_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeesRequest) ProtoMessage() {}

func (x *UpdateEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeesRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_counterparty_employee_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmployeesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeesRequest) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_counterparty_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_counterparty_employee_proto_rawDescGZIP(), []int{4}
}

func (x *UserID) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_counterparty_employee_proto protoreflect.FileDescriptor

const file_counterparty_employee_proto_rawDesc = "" +
	"\n" +
	"\x1bcounterparty/employee.proto\x12\fcounterparty\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"Y\n" +
	"\x11EmployeesResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\temployees\x18\n" +
	" \x03(\v2\x16.counterparty.EmployeeR\temployees\"\xf9\x03\n" +
	"\bEmployee\x12\"\n" +
	"\x02ID\x18\x01 \x01(\x03B\x12\x92A\f\x9a\x02\x01\x03\xa2\x02\x05int64\xe0A\x02R\x02id\x12'\n" +
	"\x0eCounterpartyID\x18\x03 \x01(\x03R\x0fcounterparty_id\x12\x1a\n" +
	"\bPosition\x18\x06 \x01(\tR\bposition\x12#\n" +
	"\fPositionType\x18\t \x01(\tR\rposition_type\x12!\n" +
	"\vContourType\x18\f \x01(\tR\fcontour_type\x120\n" +
	"\x05Start\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x123\n" +
	"\x04Stop\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04stop\x88\x01\x01\x12\x1c\n" +
	"\x06UserID\x18\x15 \x01(\x03H\x01R\auser_id\x88\x01\x01\x12 \n" +
	"\bUserName\x18\x18 \x01(\tH\x02R\tuser_name\x88\x01\x01\x129\n" +
	"\tCreatedAt\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x129\n" +
	"\tUpdatedAt\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_atB\a\n" +
	"\x05_StopB\t\n" +
	"\a_UserIDB\v\n" +
	"\t_UserName\"\xe4\x02\n" +
	"\x12AddEmployeeRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\x92A\f\x9a\x02\x01\x03\xa2\x02\x05int64\xe0A\x02R\x02id\x12\x1a\n" +
	"\bPosition\x18\x03 \x01(\tR\bposition\x12#\n" +
	"\fPositionType\x18\x05 \x01(\tR\rposition_type\x12!\n" +
	"\vContourType\x18\a \x01(\tR\fcontour_type\x120\n" +
	"\x05Start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x123\n" +
	"\x04Stop\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04stop\x88\x01\x01\x12\x1c\n" +
	"\x06UserID\x18\r \x01(\x03H\x01R\auser_id\x88\x01\x01\x12 \n" +
	"\bUserName\x18\x0f \x01(\tH\x02R\tuser_name\x88\x01\x01B\a\n" +
	"\x05_StopB\t\n" +
	"\a_UserIDB\v\n" +
	"\t_UserName\"r\n" +
	"\x16UpdateEmployeesRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\x92A\f\x9a\x02\x01\x03\xa2\x02\x05int64\xe0A\x02R\x02id\x124\n" +
	"\temployees\x18\n" +
	" \x03(\v2\x16.counterparty.EmployeeR\temployees\"1\n" +
	"\x06UserID\x12'\n" +
	"\auser_id\x18\x01 \x01(\x03B\x12\x92A\f\x9a\x02\x01\x03\xa2\x02\x05int64\xe0A\x02R\x02idB,Z*github.com/COTBU/sotbisrv/api/counterpartyb\x06proto3"

var (
	file_counterparty_employee_proto_rawDescOnce sync.Once
	file_counterparty_employee_proto_rawDescData []byte
)

func file_counterparty_employee_proto_rawDescGZIP() []byte {
	file_counterparty_employee_proto_rawDescOnce.Do(func() {
		file_counterparty_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_counterparty_employee_proto_rawDesc), len(file_counterparty_employee_proto_rawDesc)))
	})
	return file_counterparty_employee_proto_rawDescData
}

var (
	file_counterparty_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
	file_counterparty_employee_proto_goTypes  = []any{
		(*EmployeesResponse)(nil),      // 0: counterparty.EmployeesResponse
		(*Employee)(nil),               // 1: counterparty.Employee
		(*AddEmployeeRequest)(nil),     // 2: counterparty.AddEmployeeRequest
		(*UpdateEmployeesRequest)(nil), // 3: counterparty.UpdateEmployeesRequest
		(*UserID)(nil),                 // 4: counterparty.UserID
		(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	}
)
var file_counterparty_employee_proto_depIdxs = []int32{
	1, // 0: counterparty.EmployeesResponse.employees:type_name -> counterparty.Employee
	5, // 1: counterparty.Employee.Start:type_name -> google.protobuf.Timestamp
	5, // 2: counterparty.Employee.Stop:type_name -> google.protobuf.Timestamp
	5, // 3: counterparty.Employee.CreatedAt:type_name -> google.protobuf.Timestamp
	5, // 4: counterparty.Employee.UpdatedAt:type_name -> google.protobuf.Timestamp
	5, // 5: counterparty.AddEmployeeRequest.Start:type_name -> google.protobuf.Timestamp
	5, // 6: counterparty.AddEmployeeRequest.Stop:type_name -> google.protobuf.Timestamp
	1, // 7: counterparty.UpdateEmployeesRequest.employees:type_name -> counterparty.Employee
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_counterparty_employee_proto_init() }
func file_counterparty_employee_proto_init() {
	if File_counterparty_employee_proto != nil {
		return
	}
	file_counterparty_employee_proto_msgTypes[1].OneofWrappers = []any{}
	file_counterparty_employee_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_counterparty_employee_proto_rawDesc), len(file_counterparty_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_counterparty_employee_proto_goTypes,
		DependencyIndexes: file_counterparty_employee_proto_depIdxs,
		MessageInfos:      file_counterparty_employee_proto_msgTypes,
	}.Build()
	File_counterparty_employee_proto = out.File
	file_counterparty_employee_proto_goTypes = nil
	file_counterparty_employee_proto_depIdxs = nil
}
