// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: counterparty/service.proto

package counterparty

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Headers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=Values,json=values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Headers) Reset() {
	*x = Headers{}
	mi := &file_counterparty_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_counterparty_service_proto_rawDescGZIP(), []int{0}
}

func (x *Headers) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Headers) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=Paths,json=paths,proto3" json:"Paths,omitempty"`
	Headers       []*Headers             `protobuf:"bytes,2,rep,name=Headers,json=headers,proto3" json:"Headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_counterparty_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_counterparty_service_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Request) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Rules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request       *Request               `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rules) Reset() {
	*x = Rules{}
	mi := &file_counterparty_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rules) ProtoMessage() {}

func (x *Rules) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rules.ProtoReflect.Descriptor instead.
func (*Rules) Descriptor() ([]byte, []int) {
	return file_counterparty_service_proto_rawDescGZIP(), []int{2}
}

func (x *Rules) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rules) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type AuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	AllowRules    []*Rules               `protobuf:"bytes,2,rep,name=AllowRules,json=allow_rules,proto3" json:"AllowRules,omitempty"`
	DenyRules     []*Rules               `protobuf:"bytes,3,rep,name=DenyRules,json=deny_rules,proto3" json:"DenyRules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_counterparty_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_counterparty_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_counterparty_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuthMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthMessage) GetAllowRules() []*Rules {
	if x != nil {
		return x.AllowRules
	}
	return nil
}

func (x *AuthMessage) GetDenyRules() []*Rules {
	if x != nil {
		return x.DenyRules
	}
	return nil
}

var File_counterparty_service_proto protoreflect.FileDescriptor

const file_counterparty_service_proto_rawDesc = "" +
	"\n" +
	"\x1acounterparty/service.proto\x12\fcounterparty\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19counterparty/common.proto\x1a\x1fcounterparty/counterparty.proto\x1a\x1ecounterparty/bank_detail.proto\x1a\x1bcounterparty/employee.proto\x1a\x1cgoogle/api/annotations.proto\"3\n" +
	"\aHeaders\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06Values\x18\x02 \x03(\tR\x06values\"P\n" +
	"\aRequest\x12\x14\n" +
	"\x05Paths\x18\x01 \x03(\tR\x05paths\x12/\n" +
	"\aHeaders\x18\x02 \x03(\v2\x15.counterparty.HeadersR\aheaders\"L\n" +
	"\x05Rules\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\arequest\x18\x02 \x01(\v2\x15.counterparty.RequestR\arequest\"\x8b\x01\n" +
	"\vAuthMessage\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\n" +
	"AllowRules\x18\x02 \x03(\v2\x13.counterparty.RulesR\vallow_rules\x122\n" +
	"\tDenyRules\x18\x03 \x03(\v2\x13.counterparty.RulesR\n" +
	"deny_rules2\x95\x0e\n" +
	"\x0eCounterparties\x12u\n" +
	"\x11GetCounterparties\x12\x16.google.protobuf.Empty\x1a$.counterparty.CounterpartiesResponse\"\"\x82\xd3\xe4\x93\x02\x1cb\x05items\x12\x13/api/counterparties\x12v\n" +
	"\x12CreateCounterparty\x12$.counterparty.AddCounterpartyRequest\x1a\x1a.counterparty.Counterparty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/counterparties\x12Q\n" +
	"\x17GetCounterpartiesStream\x12\x16.google.protobuf.Empty\x1a\x1a.counterparty.Counterparty\"\x000\x01\x12q\n" +
	"\x13GetCounterpartyByID\x12\x1c.counterparty.CounterpartyID\x1a\x1a.counterparty.Counterparty\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/counterparties/{id}\x12m\n" +
	"\x13ArchiveCounterparty\x12\x1c.counterparty.CounterpartyID\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/counterparties/{id}\x12~\n" +
	"\x12UpdateCounterparty\x12'.counterparty.UpdateCounterpartyRequest\x1a\x1a.counterparty.Counterparty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/counterparties/{id}\x12\x9e\x01\n" +
	"\x1eGetBankDetailsByCounterpartyID\x12\x1c.counterparty.CounterpartyID\x1a!.counterparty.BankDetailsResponse\";\x82\xd3\xe4\x93\x025b\fbank_details\x12%/api/counterparties/{id}/bank_details\x12\x9e\x01\n" +
	"\x11UpdateBankDetails\x12&.counterparty.UpdateBankDetailsRequest\x1a!.counterparty.BankDetailsResponse\">\x82\xd3\xe4\x93\x028:\x01*b\fbank_details\x1a%/api/counterparties/{id}/bank_details\x12\x94\x01\n" +
	"\x1cGetEmployeesByCounterpartyID\x12\x1c.counterparty.CounterpartyID\x1a\x1f.counterparty.EmployeesResponse\"5\x82\xd3\xe4\x93\x02/b\temployees\x12\"/api/counterparties/{id}/employees\x12\x89\x01\n" +
	"\x14GetEmployeesByUserID\x12\x14.counterparty.UserID\x1a\x1f.counterparty.EmployeesResponse\":\x82\xd3\xe4\x93\x024b\temployees\x12'/api/counterparties/employees/{user_id}\x12\x92\x01\n" +
	"\x0fUpdateEmployees\x12$.counterparty.UpdateEmployeesRequest\x1a\x1f.counterparty.EmployeesResponse\"8\x82\xd3\xe4\x93\x022:\x01*b\temployees\x1a\"/api/counterparties/{id}/employees\x12\x9a\x01\n" +
	"\x17UpdateEmployeesByUserID\x12$.counterparty.UpdateEmployeesRequest\x1a\x1f.counterparty.EmployeesResponse\"8\x82\xd3\xe4\x93\x022:\x01*b\temployees\x1a\"/api/counterparties/employees/{id}\x12`\n" +
	"\bGetRules\x12\x16.google.protobuf.Empty\x1a\x19.counterparty.AuthMessage\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/counterparties/rules\x12f\n" +
	"\vUpdateRules\x12\x19.counterparty.AuthMessage\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/counterparties/rulesB1Z/github.com/COTBU/sotbi.lib/pkg/api/counterpartyb\x06proto3"

var (
	file_counterparty_service_proto_rawDescOnce sync.Once
	file_counterparty_service_proto_rawDescData []byte
)

func file_counterparty_service_proto_rawDescGZIP() []byte {
	file_counterparty_service_proto_rawDescOnce.Do(func() {
		file_counterparty_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_counterparty_service_proto_rawDesc), len(file_counterparty_service_proto_rawDesc)))
	})
	return file_counterparty_service_proto_rawDescData
}

var file_counterparty_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_counterparty_service_proto_goTypes = []any{
	(*Headers)(nil),                   // 0: counterparty.Headers
	(*Request)(nil),                   // 1: counterparty.Request
	(*Rules)(nil),                     // 2: counterparty.Rules
	(*AuthMessage)(nil),               // 3: counterparty.AuthMessage
	(*emptypb.Empty)(nil),             // 4: google.protobuf.Empty
	(*AddCounterpartyRequest)(nil),    // 5: counterparty.AddCounterpartyRequest
	(*CounterpartyID)(nil),            // 6: counterparty.CounterpartyID
	(*UpdateCounterpartyRequest)(nil), // 7: counterparty.UpdateCounterpartyRequest
	(*UpdateBankDetailsRequest)(nil),  // 8: counterparty.UpdateBankDetailsRequest
	(*UserID)(nil),                    // 9: counterparty.UserID
	(*UpdateEmployeesRequest)(nil),    // 10: counterparty.UpdateEmployeesRequest
	(*CounterpartiesResponse)(nil),    // 11: counterparty.CounterpartiesResponse
	(*Counterparty)(nil),              // 12: counterparty.Counterparty
	(*BankDetailsResponse)(nil),       // 13: counterparty.BankDetailsResponse
	(*EmployeesResponse)(nil),         // 14: counterparty.EmployeesResponse
}
var file_counterparty_service_proto_depIdxs = []int32{
	0,  // 0: counterparty.Request.Headers:type_name -> counterparty.Headers
	1,  // 1: counterparty.Rules.request:type_name -> counterparty.Request
	2,  // 2: counterparty.AuthMessage.AllowRules:type_name -> counterparty.Rules
	2,  // 3: counterparty.AuthMessage.DenyRules:type_name -> counterparty.Rules
	4,  // 4: counterparty.Counterparties.GetCounterparties:input_type -> google.protobuf.Empty
	5,  // 5: counterparty.Counterparties.CreateCounterparty:input_type -> counterparty.AddCounterpartyRequest
	4,  // 6: counterparty.Counterparties.GetCounterpartiesStream:input_type -> google.protobuf.Empty
	6,  // 7: counterparty.Counterparties.GetCounterpartyByID:input_type -> counterparty.CounterpartyID
	6,  // 8: counterparty.Counterparties.ArchiveCounterparty:input_type -> counterparty.CounterpartyID
	7,  // 9: counterparty.Counterparties.UpdateCounterparty:input_type -> counterparty.UpdateCounterpartyRequest
	6,  // 10: counterparty.Counterparties.GetBankDetailsByCounterpartyID:input_type -> counterparty.CounterpartyID
	8,  // 11: counterparty.Counterparties.UpdateBankDetails:input_type -> counterparty.UpdateBankDetailsRequest
	6,  // 12: counterparty.Counterparties.GetEmployeesByCounterpartyID:input_type -> counterparty.CounterpartyID
	9,  // 13: counterparty.Counterparties.GetEmployeesByUserID:input_type -> counterparty.UserID
	10, // 14: counterparty.Counterparties.UpdateEmployees:input_type -> counterparty.UpdateEmployeesRequest
	10, // 15: counterparty.Counterparties.UpdateEmployeesByUserID:input_type -> counterparty.UpdateEmployeesRequest
	4,  // 16: counterparty.Counterparties.GetRules:input_type -> google.protobuf.Empty
	3,  // 17: counterparty.Counterparties.UpdateRules:input_type -> counterparty.AuthMessage
	11, // 18: counterparty.Counterparties.GetCounterparties:output_type -> counterparty.CounterpartiesResponse
	12, // 19: counterparty.Counterparties.CreateCounterparty:output_type -> counterparty.Counterparty
	12, // 20: counterparty.Counterparties.GetCounterpartiesStream:output_type -> counterparty.Counterparty
	12, // 21: counterparty.Counterparties.GetCounterpartyByID:output_type -> counterparty.Counterparty
	4,  // 22: counterparty.Counterparties.ArchiveCounterparty:output_type -> google.protobuf.Empty
	12, // 23: counterparty.Counterparties.UpdateCounterparty:output_type -> counterparty.Counterparty
	13, // 24: counterparty.Counterparties.GetBankDetailsByCounterpartyID:output_type -> counterparty.BankDetailsResponse
	13, // 25: counterparty.Counterparties.UpdateBankDetails:output_type -> counterparty.BankDetailsResponse
	14, // 26: counterparty.Counterparties.GetEmployeesByCounterpartyID:output_type -> counterparty.EmployeesResponse
	14, // 27: counterparty.Counterparties.GetEmployeesByUserID:output_type -> counterparty.EmployeesResponse
	14, // 28: counterparty.Counterparties.UpdateEmployees:output_type -> counterparty.EmployeesResponse
	14, // 29: counterparty.Counterparties.UpdateEmployeesByUserID:output_type -> counterparty.EmployeesResponse
	3,  // 30: counterparty.Counterparties.GetRules:output_type -> counterparty.AuthMessage
	4,  // 31: counterparty.Counterparties.UpdateRules:output_type -> google.protobuf.Empty
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_counterparty_service_proto_init() }
func file_counterparty_service_proto_init() {
	if File_counterparty_service_proto != nil {
		return
	}
	file_counterparty_common_proto_init()
	file_counterparty_counterparty_proto_init()
	file_counterparty_bank_detail_proto_init()
	file_counterparty_employee_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_counterparty_service_proto_rawDesc), len(file_counterparty_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_counterparty_service_proto_goTypes,
		DependencyIndexes: file_counterparty_service_proto_depIdxs,
		MessageInfos:      file_counterparty_service_proto_msgTypes,
	}.Build()
	File_counterparty_service_proto = out.File
	file_counterparty_service_proto_goTypes = nil
	file_counterparty_service_proto_depIdxs = nil
}
