// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/excel_gen/excel_gen.proto

package excel_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExcelGenService_Generate_FullMethodName  = "/excel_gen.ExcelGenService/Generate"
	ExcelGenService_GetStatus_FullMethodName = "/excel_gen.ExcelGenService/GetStatus"
	ExcelGenService_GetFile_FullMethodName   = "/excel_gen.ExcelGenService/GetFile"
)

// ExcelGenServiceClient is the client API for ExcelGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExcelGenServiceClient interface {
	Generate(ctx context.Context, in *ExcelGenRequest, opts ...grpc.CallOption) (*ExcelGenResponse, error)
	GetStatus(ctx context.Context, in *ExcelGenStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExcelGenResponse], error)
	GetFile(ctx context.Context, in *ExcelGenStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExcelFileResponse], error)
}

type excelGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExcelGenServiceClient(cc grpc.ClientConnInterface) ExcelGenServiceClient {
	return &excelGenServiceClient{cc}
}

func (c *excelGenServiceClient) Generate(ctx context.Context, in *ExcelGenRequest, opts ...grpc.CallOption) (*ExcelGenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExcelGenResponse)
	err := c.cc.Invoke(ctx, ExcelGenService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *excelGenServiceClient) GetStatus(ctx context.Context, in *ExcelGenStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExcelGenResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExcelGenService_ServiceDesc.Streams[0], ExcelGenService_GetStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExcelGenStatusRequest, ExcelGenResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExcelGenService_GetStatusClient = grpc.ServerStreamingClient[ExcelGenResponse]

func (c *excelGenServiceClient) GetFile(ctx context.Context, in *ExcelGenStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExcelFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExcelGenService_ServiceDesc.Streams[1], ExcelGenService_GetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExcelGenStatusRequest, ExcelFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExcelGenService_GetFileClient = grpc.ServerStreamingClient[ExcelFileResponse]

// ExcelGenServiceServer is the server API for ExcelGenService service.
// All implementations must embed UnimplementedExcelGenServiceServer
// for forward compatibility.
type ExcelGenServiceServer interface {
	Generate(context.Context, *ExcelGenRequest) (*ExcelGenResponse, error)
	GetStatus(*ExcelGenStatusRequest, grpc.ServerStreamingServer[ExcelGenResponse]) error
	GetFile(*ExcelGenStatusRequest, grpc.ServerStreamingServer[ExcelFileResponse]) error
	mustEmbedUnimplementedExcelGenServiceServer()
}

// UnimplementedExcelGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExcelGenServiceServer struct{}

func (UnimplementedExcelGenServiceServer) Generate(context.Context, *ExcelGenRequest) (*ExcelGenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedExcelGenServiceServer) GetStatus(*ExcelGenStatusRequest, grpc.ServerStreamingServer[ExcelGenResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedExcelGenServiceServer) GetFile(*ExcelGenStatusRequest, grpc.ServerStreamingServer[ExcelFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedExcelGenServiceServer) mustEmbedUnimplementedExcelGenServiceServer() {}
func (UnimplementedExcelGenServiceServer) testEmbeddedByValue()                         {}

// UnsafeExcelGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExcelGenServiceServer will
// result in compilation errors.
type UnsafeExcelGenServiceServer interface {
	mustEmbedUnimplementedExcelGenServiceServer()
}

func RegisterExcelGenServiceServer(s grpc.ServiceRegistrar, srv ExcelGenServiceServer) {
	// If the following call pancis, it indicates UnimplementedExcelGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExcelGenService_ServiceDesc, srv)
}

func _ExcelGenService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExcelGenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExcelGenServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExcelGenService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExcelGenServiceServer).Generate(ctx, req.(*ExcelGenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExcelGenService_GetStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExcelGenStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExcelGenServiceServer).GetStatus(m, &grpc.GenericServerStream[ExcelGenStatusRequest, ExcelGenResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExcelGenService_GetStatusServer = grpc.ServerStreamingServer[ExcelGenResponse]

func _ExcelGenService_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExcelGenStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExcelGenServiceServer).GetFile(m, &grpc.GenericServerStream[ExcelGenStatusRequest, ExcelFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExcelGenService_GetFileServer = grpc.ServerStreamingServer[ExcelFileResponse]

// ExcelGenService_ServiceDesc is the grpc.ServiceDesc for ExcelGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExcelGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "excel_gen.ExcelGenService",
	HandlerType: (*ExcelGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _ExcelGenService_Generate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStatus",
			Handler:       _ExcelGenService_GetStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _ExcelGenService_GetFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/excel_gen/excel_gen.proto",
}
