// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/excel_gen/excel_gen.proto

package excel_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_REGISTERED Status = 0
	Status_INVALID    Status = 1
	Status_PROCESSING Status = 2
	Status_PROCESSED  Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "REGISTERED",
		1: "INVALID",
		2: "PROCESSING",
		3: "PROCESSED",
	}
	Status_value = map[string]int32{
		"REGISTERED": 0,
		"INVALID":    1,
		"PROCESSING": 2,
		"PROCESSED":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_excel_gen_excel_gen_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_excel_gen_excel_gen_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_CALCULATIONS            Type = 0
	Type_CALCULATIONS_SUMS       Type = 1
	Type_COSTS                   Type = 2
	Type_DEBTORS_PAYMENTS_REPORT Type = 3
	Type_DEBTORS_PAYMENTS        Type = 4
	Type_INITIATOR_PAYMENTS      Type = 5
	Type_SUBORDINATE_COSTS       Type = 6
	Type_COSTS_SUMS              Type = 7
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "CALCULATIONS",
		1: "CALCULATIONS_SUMS",
		2: "COSTS",
		3: "DEBTORS_PAYMENTS_REPORT",
		4: "DEBTORS_PAYMENTS",
		5: "INITIATOR_PAYMENTS",
		6: "SUBORDINATE_COSTS",
		7: "COSTS_SUMS",
	}
	Type_value = map[string]int32{
		"CALCULATIONS":            0,
		"CALCULATIONS_SUMS":       1,
		"COSTS":                   2,
		"DEBTORS_PAYMENTS_REPORT": 3,
		"DEBTORS_PAYMENTS":        4,
		"INITIATOR_PAYMENTS":      5,
		"SUBORDINATE_COSTS":       6,
		"COSTS_SUMS":              7,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_excel_gen_excel_gen_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_api_excel_gen_excel_gen_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{1}
}

type ExcelGenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=excel_gen.Type" json:"type,omitempty"`
	User  uint64                 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	// Deprecated: Marked as deprecated in api/excel_gen/excel_gen.proto.
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Recipients    []string               `protobuf:"bytes,5,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Meta          []byte                 `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelGenRequest) Reset() {
	*x = ExcelGenRequest{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelGenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelGenRequest) ProtoMessage() {}

func (x *ExcelGenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelGenRequest.ProtoReflect.Descriptor instead.
func (*ExcelGenRequest) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{0}
}

func (x *ExcelGenRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_CALCULATIONS
}

func (x *ExcelGenRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

// Deprecated: Marked as deprecated in api/excel_gen/excel_gen.proto.
func (x *ExcelGenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExcelGenRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExcelGenRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ExcelGenRequest) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ExcelGenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=excel_gen.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelGenResponse) Reset() {
	*x = ExcelGenResponse{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelGenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelGenResponse) ProtoMessage() {}

func (x *ExcelGenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelGenResponse.ProtoReflect.Descriptor instead.
func (*ExcelGenResponse) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{1}
}

func (x *ExcelGenResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ExcelGenResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_REGISTERED
}

type ExcelGenStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelGenStatusRequest) Reset() {
	*x = ExcelGenStatusRequest{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelGenStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelGenStatusRequest) ProtoMessage() {}

func (x *ExcelGenStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelGenStatusRequest.ProtoReflect.Descriptor instead.
func (*ExcelGenStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{2}
}

func (x *ExcelGenStatusRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ExcelGeneralRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TaskId     *uint64                `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	Data       *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Template   string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Recipients []string               `protobuf:"bytes,4,rep,name=recipients,proto3" json:"recipients,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are valid to be assigned to Items:
	//
	//	*ExcelGeneralRequest_CostWithDebtors
	//	*ExcelGeneralRequest_ProjectsAndDebtors
	//	*ExcelGeneralRequest_InitiatorPayments
	Items         isExcelGeneralRequest_Items `protobuf_oneof:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelGeneralRequest) Reset() {
	*x = ExcelGeneralRequest{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelGeneralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelGeneralRequest) ProtoMessage() {}

func (x *ExcelGeneralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelGeneralRequest.ProtoReflect.Descriptor instead.
func (*ExcelGeneralRequest) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{3}
}

func (x *ExcelGeneralRequest) GetTaskId() uint64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *ExcelGeneralRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExcelGeneralRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ExcelGeneralRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ExcelGeneralRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExcelGeneralRequest) GetItems() isExcelGeneralRequest_Items {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ExcelGeneralRequest) GetCostWithDebtors() *CostWithDebtors {
	if x != nil {
		if x, ok := x.Items.(*ExcelGeneralRequest_CostWithDebtors); ok {
			return x.CostWithDebtors
		}
	}
	return nil
}

func (x *ExcelGeneralRequest) GetProjectsAndDebtors() *ProjectsAndDebtors {
	if x != nil {
		if x, ok := x.Items.(*ExcelGeneralRequest_ProjectsAndDebtors); ok {
			return x.ProjectsAndDebtors
		}
	}
	return nil
}

func (x *ExcelGeneralRequest) GetInitiatorPayments() *InitiatorPaymentsRequest {
	if x != nil {
		if x, ok := x.Items.(*ExcelGeneralRequest_InitiatorPayments); ok {
			return x.InitiatorPayments
		}
	}
	return nil
}

type isExcelGeneralRequest_Items interface {
	isExcelGeneralRequest_Items()
}

type ExcelGeneralRequest_CostWithDebtors struct {
	CostWithDebtors *CostWithDebtors `protobuf:"bytes,6,opt,name=cost_with_debtors,json=costWithDebtors,proto3,oneof"`
}

type ExcelGeneralRequest_ProjectsAndDebtors struct {
	ProjectsAndDebtors *ProjectsAndDebtors `protobuf:"bytes,7,opt,name=projects_and_debtors,json=projectsAndDebtors,proto3,oneof"`
}

type ExcelGeneralRequest_InitiatorPayments struct {
	InitiatorPayments *InitiatorPaymentsRequest `protobuf:"bytes,10,opt,name=initiator_payments,json=initiatorPayments,proto3,oneof"`
}

func (*ExcelGeneralRequest_CostWithDebtors) isExcelGeneralRequest_Items() {}

func (*ExcelGeneralRequest_ProjectsAndDebtors) isExcelGeneralRequest_Items() {}

func (*ExcelGeneralRequest_InitiatorPayments) isExcelGeneralRequest_Items() {}

type InitiatorPaymentsRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*InitiatorPaymentsRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatorPaymentsRequest) Reset() {
	*x = InitiatorPaymentsRequest{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatorPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatorPaymentsRequest) ProtoMessage() {}

func (x *InitiatorPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatorPaymentsRequest.ProtoReflect.Descriptor instead.
func (*InitiatorPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{4}
}

func (x *InitiatorPaymentsRequest) GetItems() []*InitiatorPaymentsRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CostWithDebtors struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*CostWithDebtors_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostWithDebtors) Reset() {
	*x = CostWithDebtors{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostWithDebtors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostWithDebtors) ProtoMessage() {}

func (x *CostWithDebtors) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostWithDebtors.ProtoReflect.Descriptor instead.
func (*CostWithDebtors) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{5}
}

func (x *CostWithDebtors) GetItems() []*CostWithDebtors_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProjectsAndDebtors struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*ProjectsAndDebtors_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectsAndDebtors) Reset() {
	*x = ProjectsAndDebtors{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectsAndDebtors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsAndDebtors) ProtoMessage() {}

func (x *ProjectsAndDebtors) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsAndDebtors.ProtoReflect.Descriptor instead.
func (*ProjectsAndDebtors) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectsAndDebtors) GetItems() []*ProjectsAndDebtors_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type InitiatorPaymentsRequest_Item struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	BankAccount     string                 `protobuf:"bytes,2,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	Number          string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Inn             string                 `protobuf:"bytes,4,opt,name=inn,proto3" json:"inn,omitempty"`
	Account         string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Name            string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	PaymentPurpose  string                 `protobuf:"bytes,7,opt,name=payment_purpose,json=paymentPurpose,proto3" json:"payment_purpose,omitempty"`
	Debet           float64                `protobuf:"fixed64,8,opt,name=debet,proto3" json:"debet,omitempty"`
	Credit          float64                `protobuf:"fixed64,9,opt,name=credit,proto3" json:"credit,omitempty"`
	TradingCodeName string                 `protobuf:"bytes,10,opt,name=trading_code_name,json=tradingCodeName,proto3" json:"trading_code_name,omitempty"`
	LabelName       string                 `protobuf:"bytes,11,opt,name=label_name,json=labelName,proto3" json:"label_name,omitempty"`
	DepositName     string                 `protobuf:"bytes,12,opt,name=deposit_name,json=depositName,proto3" json:"deposit_name,omitempty"`
	ProjectName     string                 `protobuf:"bytes,13,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	DebtorName      string                 `protobuf:"bytes,14,opt,name=debtor_name,json=debtorName,proto3" json:"debtor_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiatorPaymentsRequest_Item) Reset() {
	*x = InitiatorPaymentsRequest_Item{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatorPaymentsRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatorPaymentsRequest_Item) ProtoMessage() {}

func (x *InitiatorPaymentsRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatorPaymentsRequest_Item.ProtoReflect.Descriptor instead.
func (*InitiatorPaymentsRequest_Item) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{4, 0}
}

func (x *InitiatorPaymentsRequest_Item) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetPaymentPurpose() string {
	if x != nil {
		return x.PaymentPurpose
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetDebet() float64 {
	if x != nil {
		return x.Debet
	}
	return 0
}

func (x *InitiatorPaymentsRequest_Item) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *InitiatorPaymentsRequest_Item) GetTradingCodeName() string {
	if x != nil {
		return x.TradingCodeName
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetLabelName() string {
	if x != nil {
		return x.LabelName
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetDepositName() string {
	if x != nil {
		return x.DepositName
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *InitiatorPaymentsRequest_Item) GetDebtorName() string {
	if x != nil {
		return x.DebtorName
	}
	return ""
}

type CostWithDebtors_Item struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Date             string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	DayOfWeek        string                 `protobuf:"bytes,6,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	UserName         string                 `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserUnit1        string                 `protobuf:"bytes,10,opt,name=user_unit1,json=userUnit1,proto3" json:"user_unit1,omitempty"`
	UserUnit2        string                 `protobuf:"bytes,12,opt,name=user_unit2,json=userUnit2,proto3" json:"user_unit2,omitempty"`
	DebtorName       string                 `protobuf:"bytes,14,opt,name=debtor_name,json=debtorName,proto3" json:"debtor_name,omitempty"`
	ProjectName      string                 `protobuf:"bytes,16,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	MinutesCosts     uint64                 `protobuf:"varint,18,opt,name=minutes_costs,json=minutesCosts,proto3" json:"minutes_costs,omitempty"`
	Description      string                 `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	WorkCategoryName string                 `protobuf:"bytes,22,opt,name=work_category_name,json=workCategoryName,proto3" json:"work_category_name,omitempty"`
	Time             string                 `protobuf:"bytes,24,opt,name=time,proto3" json:"time,omitempty"`
	DebtorGroup      string                 `protobuf:"bytes,26,opt,name=debtor_group,json=debtorGroup,proto3" json:"debtor_group,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CostWithDebtors_Item) Reset() {
	*x = CostWithDebtors_Item{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostWithDebtors_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostWithDebtors_Item) ProtoMessage() {}

func (x *CostWithDebtors_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostWithDebtors_Item.ProtoReflect.Descriptor instead.
func (*CostWithDebtors_Item) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CostWithDebtors_Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CostWithDebtors_Item) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CostWithDebtors_Item) GetDayOfWeek() string {
	if x != nil {
		return x.DayOfWeek
	}
	return ""
}

func (x *CostWithDebtors_Item) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CostWithDebtors_Item) GetUserUnit1() string {
	if x != nil {
		return x.UserUnit1
	}
	return ""
}

func (x *CostWithDebtors_Item) GetUserUnit2() string {
	if x != nil {
		return x.UserUnit2
	}
	return ""
}

func (x *CostWithDebtors_Item) GetDebtorName() string {
	if x != nil {
		return x.DebtorName
	}
	return ""
}

func (x *CostWithDebtors_Item) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CostWithDebtors_Item) GetMinutesCosts() uint64 {
	if x != nil {
		return x.MinutesCosts
	}
	return 0
}

func (x *CostWithDebtors_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CostWithDebtors_Item) GetWorkCategoryName() string {
	if x != nil {
		return x.WorkCategoryName
	}
	return ""
}

func (x *CostWithDebtors_Item) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *CostWithDebtors_Item) GetDebtorGroup() string {
	if x != nil {
		return x.DebtorGroup
	}
	return ""
}

type ProjectsAndDebtors_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Percentage    float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectsAndDebtors_Item) Reset() {
	*x = ProjectsAndDebtors_Item{}
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectsAndDebtors_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsAndDebtors_Item) ProtoMessage() {}

func (x *ProjectsAndDebtors_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_excel_gen_excel_gen_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsAndDebtors_Item.ProtoReflect.Descriptor instead.
func (*ProjectsAndDebtors_Item) Descriptor() ([]byte, []int) {
	return file_api_excel_gen_excel_gen_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ProjectsAndDebtors_Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectsAndDebtors_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectsAndDebtors_Item) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectsAndDebtors_Item) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectsAndDebtors_Item) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

var File_api_excel_gen_excel_gen_proto protoreflect.FileDescriptor

const file_api_excel_gen_excel_gen_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/excel_gen/excel_gen.proto\x12\texcel_gen\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd3\x01\n" +
	"\x0fExcelGenRequest\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.excel_gen.TypeR\x04type\x12\x12\n" +
	"\x04user\x18\x02 \x01(\x04R\x04user\x12\x18\n" +
	"\x05email\x18\x03 \x01(\tB\x02\x18\x01R\x05email\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1e\n" +
	"\n" +
	"recipients\x18\x05 \x03(\tR\n" +
	"recipients\x12\x12\n" +
	"\x04meta\x18\x06 \x01(\fR\x04meta\"V\n" +
	"\x10ExcelGenResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.excel_gen.StatusR\x06status\"0\n" +
	"\x15ExcelGenStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\xdf\x03\n" +
	"\x13ExcelGeneralRequest\x12\x1c\n" +
	"\atask_id\x18\x01 \x01(\x04H\x01R\x06taskId\x88\x01\x01\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12\x1e\n" +
	"\n" +
	"recipients\x18\x04 \x03(\tR\n" +
	"recipients\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12H\n" +
	"\x11cost_with_debtors\x18\x06 \x01(\v2\x1a.excel_gen.CostWithDebtorsH\x00R\x0fcostWithDebtors\x12Q\n" +
	"\x14projects_and_debtors\x18\a \x01(\v2\x1d.excel_gen.ProjectsAndDebtorsH\x00R\x12projectsAndDebtors\x12T\n" +
	"\x12initiator_payments\x18\n" +
	" \x01(\v2#.excel_gen.InitiatorPaymentsRequestH\x00R\x11initiatorPaymentsB\a\n" +
	"\x05itemsB\n" +
	"\n" +
	"\b_task_id\"\xfb\x03\n" +
	"\x18InitiatorPaymentsRequest\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.excel_gen.InitiatorPaymentsRequest.ItemR\x05items\x1a\x9e\x03\n" +
	"\x04Item\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12!\n" +
	"\fbank_account\x18\x02 \x01(\tR\vbankAccount\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x10\n" +
	"\x03inn\x18\x04 \x01(\tR\x03inn\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\tR\aaccount\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12'\n" +
	"\x0fpayment_purpose\x18\a \x01(\tR\x0epaymentPurpose\x12\x14\n" +
	"\x05debet\x18\b \x01(\x01R\x05debet\x12\x16\n" +
	"\x06credit\x18\t \x01(\x01R\x06credit\x12*\n" +
	"\x11trading_code_name\x18\n" +
	" \x01(\tR\x0ftradingCodeName\x12\x1d\n" +
	"\n" +
	"label_name\x18\v \x01(\tR\tlabelName\x12!\n" +
	"\fdeposit_name\x18\f \x01(\tR\vdepositName\x12!\n" +
	"\fproject_name\x18\r \x01(\tR\vprojectName\x12\x1f\n" +
	"\vdebtor_name\x18\x0e \x01(\tR\n" +
	"debtorName\"\xe0\x03\n" +
	"\x0fCostWithDebtors\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.excel_gen.CostWithDebtors.ItemR\x05items\x1a\x95\x03\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x1e\n" +
	"\vday_of_week\x18\x06 \x01(\tR\tdayOfWeek\x12\x1b\n" +
	"\tuser_name\x18\b \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_unit1\x18\n" +
	" \x01(\tR\tuserUnit1\x12\x1d\n" +
	"\n" +
	"user_unit2\x18\f \x01(\tR\tuserUnit2\x12\x1f\n" +
	"\vdebtor_name\x18\x0e \x01(\tR\n" +
	"debtorName\x12!\n" +
	"\fproject_name\x18\x10 \x01(\tR\vprojectName\x12#\n" +
	"\rminutes_costs\x18\x12 \x01(\x04R\fminutesCosts\x12 \n" +
	"\vdescription\x18\x14 \x01(\tR\vdescription\x12,\n" +
	"\x12work_category_name\x18\x16 \x01(\tR\x10workCategoryName\x12\x12\n" +
	"\x04time\x18\x18 \x01(\tR\x04time\x12!\n" +
	"\fdebtor_group\x18\x1a \x01(\tR\vdebtorGroup\"\xdd\x01\n" +
	"\x12ProjectsAndDebtors\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".excel_gen.ProjectsAndDebtors.ItemR\x05items\x1a\x8c\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x04R\tprojectId\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage*D\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"REGISTERED\x10\x00\x12\v\n" +
	"\aINVALID\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\r\n" +
	"\tPROCESSED\x10\x03*\xac\x01\n" +
	"\x04Type\x12\x10\n" +
	"\fCALCULATIONS\x10\x00\x12\x15\n" +
	"\x11CALCULATIONS_SUMS\x10\x01\x12\t\n" +
	"\x05COSTS\x10\x02\x12\x1b\n" +
	"\x17DEBTORS_PAYMENTS_REPORT\x10\x03\x12\x14\n" +
	"\x10DEBTORS_PAYMENTS\x10\x04\x12\x16\n" +
	"\x12INITIATOR_PAYMENTS\x10\x05\x12\x15\n" +
	"\x11SUBORDINATE_COSTS\x10\x06\x12\x0e\n" +
	"\n" +
	"COSTS_SUMS\x10\a2\xf2\x01\n" +
	"\x0fExcelGenService\x12N\n" +
	"\x0fGeneralGenerate\x12\x1e.excel_gen.ExcelGeneralRequest\x1a\x1b.excel_gen.ExcelGenResponse\x12C\n" +
	"\bGenerate\x12\x1a.excel_gen.ExcelGenRequest\x1a\x1b.excel_gen.ExcelGenResponse\x12J\n" +
	"\tGetStatus\x12 .excel_gen.ExcelGenStatusRequest\x1a\x1b.excel_gen.ExcelGenResponseB.Z,github.com/COTBU/sotbi.lib/pkg/api/excel_genb\x06proto3"

var (
	file_api_excel_gen_excel_gen_proto_rawDescOnce sync.Once
	file_api_excel_gen_excel_gen_proto_rawDescData []byte
)

func file_api_excel_gen_excel_gen_proto_rawDescGZIP() []byte {
	file_api_excel_gen_excel_gen_proto_rawDescOnce.Do(func() {
		file_api_excel_gen_excel_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_excel_gen_excel_gen_proto_rawDesc), len(file_api_excel_gen_excel_gen_proto_rawDesc)))
	})
	return file_api_excel_gen_excel_gen_proto_rawDescData
}

var file_api_excel_gen_excel_gen_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_excel_gen_excel_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_excel_gen_excel_gen_proto_goTypes = []any{
	(Status)(0),                           // 0: excel_gen.Status
	(Type)(0),                             // 1: excel_gen.Type
	(*ExcelGenRequest)(nil),               // 2: excel_gen.ExcelGenRequest
	(*ExcelGenResponse)(nil),              // 3: excel_gen.ExcelGenResponse
	(*ExcelGenStatusRequest)(nil),         // 4: excel_gen.ExcelGenStatusRequest
	(*ExcelGeneralRequest)(nil),           // 5: excel_gen.ExcelGeneralRequest
	(*InitiatorPaymentsRequest)(nil),      // 6: excel_gen.InitiatorPaymentsRequest
	(*CostWithDebtors)(nil),               // 7: excel_gen.CostWithDebtors
	(*ProjectsAndDebtors)(nil),            // 8: excel_gen.ProjectsAndDebtors
	(*InitiatorPaymentsRequest_Item)(nil), // 9: excel_gen.InitiatorPaymentsRequest.Item
	(*CostWithDebtors_Item)(nil),          // 10: excel_gen.CostWithDebtors.Item
	(*ProjectsAndDebtors_Item)(nil),       // 11: excel_gen.ProjectsAndDebtors.Item
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*structpb.Struct)(nil),               // 13: google.protobuf.Struct
}
var file_api_excel_gen_excel_gen_proto_depIdxs = []int32{
	1,  // 0: excel_gen.ExcelGenRequest.type:type_name -> excel_gen.Type
	12, // 1: excel_gen.ExcelGenRequest.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: excel_gen.ExcelGenResponse.status:type_name -> excel_gen.Status
	13, // 3: excel_gen.ExcelGeneralRequest.data:type_name -> google.protobuf.Struct
	12, // 4: excel_gen.ExcelGeneralRequest.created_at:type_name -> google.protobuf.Timestamp
	7,  // 5: excel_gen.ExcelGeneralRequest.cost_with_debtors:type_name -> excel_gen.CostWithDebtors
	8,  // 6: excel_gen.ExcelGeneralRequest.projects_and_debtors:type_name -> excel_gen.ProjectsAndDebtors
	6,  // 7: excel_gen.ExcelGeneralRequest.initiator_payments:type_name -> excel_gen.InitiatorPaymentsRequest
	9,  // 8: excel_gen.InitiatorPaymentsRequest.items:type_name -> excel_gen.InitiatorPaymentsRequest.Item
	10, // 9: excel_gen.CostWithDebtors.items:type_name -> excel_gen.CostWithDebtors.Item
	11, // 10: excel_gen.ProjectsAndDebtors.items:type_name -> excel_gen.ProjectsAndDebtors.Item
	5,  // 11: excel_gen.ExcelGenService.GeneralGenerate:input_type -> excel_gen.ExcelGeneralRequest
	2,  // 12: excel_gen.ExcelGenService.Generate:input_type -> excel_gen.ExcelGenRequest
	4,  // 13: excel_gen.ExcelGenService.GetStatus:input_type -> excel_gen.ExcelGenStatusRequest
	3,  // 14: excel_gen.ExcelGenService.GeneralGenerate:output_type -> excel_gen.ExcelGenResponse
	3,  // 15: excel_gen.ExcelGenService.Generate:output_type -> excel_gen.ExcelGenResponse
	3,  // 16: excel_gen.ExcelGenService.GetStatus:output_type -> excel_gen.ExcelGenResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_excel_gen_excel_gen_proto_init() }
func file_api_excel_gen_excel_gen_proto_init() {
	if File_api_excel_gen_excel_gen_proto != nil {
		return
	}
	file_api_excel_gen_excel_gen_proto_msgTypes[3].OneofWrappers = []any{
		(*ExcelGeneralRequest_CostWithDebtors)(nil),
		(*ExcelGeneralRequest_ProjectsAndDebtors)(nil),
		(*ExcelGeneralRequest_InitiatorPayments)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_excel_gen_excel_gen_proto_rawDesc), len(file_api_excel_gen_excel_gen_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_excel_gen_excel_gen_proto_goTypes,
		DependencyIndexes: file_api_excel_gen_excel_gen_proto_depIdxs,
		EnumInfos:         file_api_excel_gen_excel_gen_proto_enumTypes,
		MessageInfos:      file_api_excel_gen_excel_gen_proto_msgTypes,
	}.Build()
	File_api_excel_gen_excel_gen_proto = out.File
	file_api_excel_gen_excel_gen_proto_goTypes = nil
	file_api_excel_gen_excel_gen_proto_depIdxs = nil
}
