package uuid

import (
	"crypto/md5" //nolint:gosec // не криптография: деривация UUID v3
	"hash"
	"uuid"
)

var NameSpaceDNS = uuid.MustParse("6ba7b810-9dad-11d1-80b4-00c04fd430c8")

// newHash returns a new UUID derived from the hash of space concatenated with
// data generated by h.  The hash should be at least 16 byte in length.  The
// first 16 bytes of the hash are used to form the UUID.  The version of the
// UUID will be the lower 4 bits of version.  NewHash is used to implement
// NewMD5 and NewSHA1.
func newHash(h hash.Hash, space uuid.UUID, data []byte, version int) uuid.UUID {
	h.Reset()
	h.Write(space[:])
	h.Write(data)
	s := h.Sum(nil)

	var uuid uuid.UUID
	copy(uuid[:], s)
	uuid[6] = (uuid[6] & 0x0f) | uint8((version&0xf)<<4)
	uuid[8] = (uuid[8] & 0x3f) | 0x80 // RFC 4122 variant

	return uuid
}

// NewMD5 returns a new MD5 (Version 3) UUID based on the
// supplied name space and data.  It is the same as calling:
//
//	NewHash(md5.New(), space, data, 3)
func NewMD5(space uuid.UUID, data []byte) uuid.UUID {
	return newHash(md5.New(), space, data, 3) //nolint:gosec // не криптография: деривация UUID v3
}
