// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/notification/notification.proto

// edition = "2023";

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Определение перечисления NotificationType
type NotificationType int32

const (
	NotificationType_EMAIL    NotificationType = 0 // Уведомление на почту
	NotificationType_TELEGRAM NotificationType = 1 // Уведомление в телеграмм
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "EMAIL",
		1: "TELEGRAM",
	}
	NotificationType_value = map[string]int32{
		"EMAIL":    0,
		"TELEGRAM": 1,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notification_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_api_notification_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{0}
}

// Определение сообщения Notification
type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  NotificationType       `protobuf:"varint,1,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	// Теиа письма
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"` // [(validate.rules).string.min_len = 2];
	// Само сообщение
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// список получателей
	Recipients []string `protobuf:"bytes,4,rep,name=recipients,proto3" json:"recipients,omitempty"` // [(validate.rules).repeated.items.string.email = true];
	// название объекта, в котором лежит вложение
	ObjectName    string `protobuf:"bytes,5,opt,name=objectName,proto3" json:"objectName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_EMAIL
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Notification) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *Notification) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

var File_api_notification_notification_proto protoreflect.FileDescriptor

const file_api_notification_notification_proto_rawDesc = "" +
	"\n" +
	"#api/notification/notification.proto\x12\fnotification\x1a google/protobuf/descriptor.proto\"\xb0\x01\n" +
	"\fNotification\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1e\n" +
	"\n" +
	"recipients\x18\x04 \x03(\tR\n" +
	"recipients\x12\x1e\n" +
	"\n" +
	"objectName\x18\x05 \x01(\tR\n" +
	"objectName*+\n" +
	"\x10NotificationType\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\f\n" +
	"\bTELEGRAM\x10\x01B-Z+github.com/COTBU/sotbi.lib/pkg/notificationb\x06proto3"

var (
	file_api_notification_notification_proto_rawDescOnce sync.Once
	file_api_notification_notification_proto_rawDescData []byte
)

func file_api_notification_notification_proto_rawDescGZIP() []byte {
	file_api_notification_notification_proto_rawDescOnce.Do(func() {
		file_api_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notification_notification_proto_rawDesc), len(file_api_notification_notification_proto_rawDesc)))
	})
	return file_api_notification_notification_proto_rawDescData
}

var file_api_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_notification_notification_proto_goTypes = []any{
	(NotificationType)(0), // 0: notification.NotificationType
	(*Notification)(nil),  // 1: notification.Notification
}
var file_api_notification_notification_proto_depIdxs = []int32{
	0, // 0: notification.Notification.type:type_name -> notification.NotificationType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_notification_notification_proto_init() }
func file_api_notification_notification_proto_init() {
	if File_api_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notification_notification_proto_rawDesc), len(file_api_notification_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notification_notification_proto_goTypes,
		DependencyIndexes: file_api_notification_notification_proto_depIdxs,
		EnumInfos:         file_api_notification_notification_proto_enumTypes,
		MessageInfos:      file_api_notification_notification_proto_msgTypes,
	}.Build()
	File_api_notification_notification_proto = out.File
	file_api_notification_notification_proto_goTypes = nil
	file_api_notification_notification_proto_depIdxs = nil
}
