package onec

type PaymentDocument struct {
	DocumentType           string  `mapstructure:"СекцияДокумент,omitempty"       json:"document_type,omitempty"`
	Number                 string  `mapstructure:"Номер"                          json:"number,omitempty"`
	Data                   string  `mapstructure:"Дата"                           json:"date,omitempty"`
	WrittenOffDate         string  `mapstructure:"ДатаСписано,omitempty"          json:"written_off_date,omitempty"`
	IncomeDate             string  `mapstructure:"ДатаПоступило,omitempty"        json:"income_date,omitempty"`
	Summ                   float64 `mapstructure:"Сумма,omitempty"                json:"summ"`
	RectDate               string  `mapstructure:"КвитанцияДата,omitempty"        json:"rect_date,omitempty"`
	RectTime               string  `mapstructure:"КвитанцияВремя,omitempty"       json:"rect_time,omitempty"`
	RectContent            string  `mapstructure:"КвитанцияСодержание,omitempty"  json:"rect_content,omitempty"`
	PayerAccount           string  `mapstructure:"ПлательщикСчет,omitempty"       json:"payer_account,omitempty"`
	Payer                  string  `mapstructure:"Плательщик,omitempty"           json:"payer,omitempty"`
	PayerINN               string  `mapstructure:"ПлательщикИНН,omitempty"        json:"payer_inn,omitempty"`
	PayerKPP               string  `mapstructure:"ПлательщикКПП,omitempty"        json:"payer_kpp,omitempty"`
	Payer1                 *string `mapstructure:"Плательщик1,omitempty"          json:"payer1,omitempty"`
	Payer2                 *string `mapstructure:"Плательщик2,omitempty"          json:"payer2,omitempty"`
	Payer3                 *string `mapstructure:"Плательщик3,omitempty"          json:"payer3,omitempty"`
	Payer4                 *string `mapstructure:"Плательщик4,omitempty"          json:"payer4,omitempty"`
	PayerCurrentAccount    string  `mapstructure:"ПлательщикРасчСчет,omitempty"   json:"payer_current_account,omitempty"`
	PayerBank1             string  `mapstructure:"ПлательщикБанк1,omitempty"      json:"payer_bank1,omitempty"`
	PayerBank2             *string `mapstructure:"ПлательщикБанк2,omitempty"      json:"payer_bank2,omitempty"`
	PayerBIK               string  `mapstructure:"ПлательщикБИК,omitempty"        json:"payer_bik,omitempty"`
	PayerCorrAccount       string  `mapstructure:"ПлательщикКорсчет,omitempty"    json:"payer_corr_account,omitempty"`
	ReceiverAccount        string  `mapstructure:"ПолучательСчет,omitempty"       json:"receiver_account,omitempty"`
	Receiver               string  `mapstructure:"Получатель,omitempty"           json:"receiver,omitempty"`
	ReceiverINN            string  `mapstructure:"ПолучательИНН,omitempty"        json:"receiver_inn,omitempty"`
	ReceiverKPP            string  `mapstructure:"ПолучательКПП,omitempty"        json:"receiver_kpp,omitempty"`
	Receiver1              *string `mapstructure:"Получатель1,omitempty"          json:"receiver1,omitempty"`
	Receiver2              *string `mapstructure:"Получатель2,omitempty"          json:"receiver2,omitempty"`
	Receiver3              *string `mapstructure:"Получатель3,omitempty"          json:"receiver3,omitempty"`
	Receiver4              *string `mapstructure:"Получатель4,omitempty"          json:"receiver4,omitempty"`
	ReceiverCurrentAccount string  `mapstructure:"ПолучательРасчСчет,omitempty"   json:"receiver_current_account,omitempty"` //nolint:lll
	ReceiverBank1          string  `mapstructure:"ПолучательБанк1,omitempty"      json:"receiver_bank1,omitempty"`
	ReceiverBank2          *string `mapstructure:"ПолучательБанк2,omitempty"      json:"receiver_bank2,omitempty"`
	ReceiverBIK            string  `mapstructure:"ПолучательБИК,omitempty"        json:"receiver_bik,omitempty"`
	ReceiverCorrAccount    string  `mapstructure:"ПолучательКорсчет,omitempty"    json:"receiver_corr_account,omitempty"`
	PaymentType            *string `mapstructure:"ВидПлатежа,omitempty"           json:"payment_type,omitempty"`
	PaymentPurposeCode     *string `mapstructure:"КодНазПлатежа,omitempty"        json:"payment_purpose_code,omitempty"`
	UIN                    *string `mapstructure:"Код,omitempty"                  json:"uin,omitempty"`
	PaymentPurpose         string  `mapstructure:"НазначениеПлатежа,omitempty"    json:"payment_purpose,omitempty"`
	PaymentPurpose1        *string `mapstructure:"НазначениеПлатежа1,omitempty"   json:"payment_purpose1,omitempty"`
	PaymentPurpose2        *string `mapstructure:"НазначениеПлатежа2,omitempty"   json:"payment_purpose2,omitempty"`
	PaymentPurpose3        *string `mapstructure:"НазначениеПлатежа3,omitempty"   json:"payment_purpose3,omitempty"`
	PaymentPurpose4        *string `mapstructure:"НазначениеПлатежа4,omitempty"   json:"payment_purpose4,omitempty"`
	PaymentPurpose5        *string `mapstructure:"НазначениеПлатежа5,omitempty"   json:"payment_purpose5,omitempty"`
	PaymentPurpose6        *string `mapstructure:"НазначениеПлатежа6,omitempty"   json:"payment_purpose6,omitempty"`
	CompilerStatus         *string `mapstructure:"СтатусСоставителя,omitempty"    json:"compiler_status,omitempty"`
	OKATO                  *string `mapstructure:"ОКАТО,omitempty"                json:"okato,omitempty"`
	IndicatorKBK           *string `mapstructure:"ПоказательКБК,omitempty"        json:"indicator_kbk,omitempty"`
	IndicatorBasics        *string `mapstructure:"ПоказательОснования,omitempty"  json:"indicator_basics,omitempty"`
	IndicatorPeriod        *string `mapstructure:"ПоказательПериода,omitempty"    json:"indicator_period,omitempty"`
	IndicatorNumber        *string `mapstructure:"ПоказательНомера,omitempty"     json:"indicator_number,omitempty"`
	IndicatorDate          *string `mapstructure:"ПоказательДаты,omitempty"       json:"indicator_date,omitempty"`
	IndicatorType          *string `mapstructure:"ПоказательТипа,omitempty"       json:"indicator_type,omitempty"`
	Priority               *uint   `mapstructure:"Очередность,omitempty"          json:"priority,omitempty"`
	DefrayalType           *string `mapstructure:"ВидОплаты,omitempty"            json:"defrayal_type,omitempty"`
	AcceptanceTerm         *string `mapstructure:"СрокАкцепта,omitempty"          json:"acceptance_term,omitempty"`
	TypeLetterCredit       *string `mapstructure:"ВидАккредитива,omitempty"       json:"type_letter_credit,omitempty"`
	PaymentTerm            *string `mapstructure:"СрокПлатежа,omitempty"          json:"payment_term,omitempty"`
	PaymentCondition1      *string `mapstructure:"УсловиеОплаты1,omitempty"       json:"paymen_condition1,omitempty"`
	PaymentCondition2      *string `mapstructure:"УсловиеОплаты1,omitempty"       json:"paymen_condition2,omitempty"`
	PaymentCondition3      *string `mapstructure:"УсловиеОплаты1,omitempty"       json:"paymen_condition3,omitempty"`
	PaymentBy              *string `mapstructure:"ПлатежПоПредст,omitempty"       json:"payment_by,omitempty"`
	AdditionalTerms        *string `mapstructure:"ДополнУсловия,omitempty"        json:"additional_terms,omitempty"`
	SupplierAccountNumber  *string `mapstructure:"НомерСчетаПоставщика,omitempty" json:"supplier_account_number,omitempty"`
	DocumentSendingDate    *string `mapstructure:"ДатаОтсылкиДок,omitempty"       json:"document_sending_date,omitempty"`
}
